import { execFile } from "node:child_process";
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { promisify } from "node:util";
import { checkoutWorkstream, createCheckpoint, createWorkstream, getActiveWorkstream, getCheckpoint, initializeRepository, listWorkstreams, openRepository, repositoryStatus, restoreCheckpoint, stagePaths } from "./core.js";

const execFileAsync = promisify(execFile);
type Remote={name:string;url:string;fetch?:string;push?:string};
type RemoteConfig={version:1;remotes:Remote[]};
type Tag={version:1;name:string;checkpointId:string;message?:string;createdAt:string};
const internal=(root:string)=>join(root,".sessions");
const readJson=async<T>(p:string):Promise<T>=>JSON.parse(await readFile(p,"utf8"));
const writeJson=async(p:string,v:unknown)=>{await mkdir(dirname(p),{recursive:true});await writeFile(p,JSON.stringify(v,null,2)+"\n","utf8")};
const remoteFile=(root:string)=>join(internal(root),"remotes.json");
const tagDir=(root:string)=>join(internal(root),"refs","tags");
async function config(root:string):Promise<RemoteConfig>{try{return await readJson(remoteFile(root))}catch{return{version:1,remotes:[]}}}
export async function listRemotes(root:string){return(await config(root)).remotes}
export async function setRemote(root:string,name:string,url:string){await openRepository(root);const c=await config(root);const next={version:1 as const,remotes:[...c.remotes.filter(r=>r.name!==name),{name,url}]};await writeJson(remoteFile(root),next);return next.remotes.find(r=>r.name===name)!}
export async function removeRemote(root:string,name:string){const c=await config(root);await writeJson(remoteFile(root),{version:1,remotes:c.remotes.filter(r=>r.name!==name)})}
async function remote(root:string,name:string){const r=(await listRemotes(root)).find(x=>x.name===name);if(!r)throw new Error(`Unknown remote: ${name}`);return r}
export async function createTag(root:string,name:string,checkpointRef?:string,message?:string){const active=await getActiveWorkstream(root);const checkpoint=checkpointRef?await getCheckpoint(root,checkpointRef):active.headCheckpointId?await getCheckpoint(root,active.headCheckpointId):undefined;if(!checkpoint)throw new Error("Cannot tag repository without a checkpoint");const p=join(tagDir(root),`${encodeURIComponent(name)}.json`);try{await stat(p);throw new Error(`Tag already exists: ${name}`)}catch(e:any){if(e?.code!=="ENOENT")throw e}const tag:Tag={version:1,name,checkpointId:checkpoint.id,message,createdAt:new Date().toISOString()};await writeJson(p,tag);return tag}
export async function listTags(root:string):Promise<Tag[]>{try{return await Promise.all((await readdir(tagDir(root))).filter(x=>x.endsWith(".json")).map(x=>readJson<Tag>(join(tagDir(root),x))))}catch{return[]}}
export async function deleteTag(root:string,name:string){await rm(join(tagDir(root),`${encodeURIComponent(name)}.json`),{force:true})}
async function materializeHead(root:string){const active=await getActiveWorkstream(root);if(active.headCheckpointId)await restoreCheckpoint(root,active.headCheckpointId)}
export async function cloneRepository(source:string,destination:string){const src=resolve(source),dest=resolve(destination);await mkdir(dest,{recursive:true});await cp(join(src,".sessions"),join(dest,".sessions"),{recursive:true,force:true});await materializeHead(dest);return openRepository(dest)}
export async function fetchRemote(root:string,name="origin"){const r=await remote(root,name);const source=resolve(r.fetch??r.url);const incoming=join(internal(root),"remotes",name);await rm(incoming,{recursive:true,force:true});await cp(join(source,".sessions"),incoming,{recursive:true,force:true});return{remote:name,fetchedAt:new Date().toISOString(),path:incoming}}
export async function pushRemote(root:string,name="origin"){const r=await remote(root,name);const destination=resolve(r.push??r.url);await mkdir(destination,{recursive:true});await cp(join(root,".sessions"),join(destination,".sessions"),{recursive:true,force:true});return{remote:name,pushedAt:new Date().toISOString()}}
export async function pullRemote(root:string,name="origin"){const r=await remote(root,name);const status=await repositoryStatus(root);if(!status.clean)throw new Error("Cannot pull with local staged or unstaged changes");const local=await openRepository(root),source=resolve(r.fetch??r.url),upstream=await openRepository(source);if(local.id!==upstream.id)throw new Error("Remote repository identity does not match local repository");const savedRemotes=await config(root);await cp(join(source,".sessions"),join(root,".sessions"),{recursive:true,force:true});await writeJson(remoteFile(root),savedRemotes);await materializeHead(root);return{remote:name,pulledAt:new Date().toISOString(),headCheckpointId:(await getActiveWorkstream(root)).headCheckpointId}}
export async function revertCheckpoint(root:string,reference:string,name?:string){const status=await repositoryStatus(root);if(!status.clean)throw new Error("Cannot revert with local staged or unstaged changes");const active=await getActiveWorkstream(root);if(!active.headCheckpointId)throw new Error("Cannot revert without a current checkpoint");const before=await getCheckpoint(root,active.headCheckpointId),target=await getCheckpoint(root,reference);await restoreCheckpoint(root,target.id);await stagePaths(root,["."]);const reverted=await createCheckpoint(root,{friendlyName:name??`Revert ${target.friendlyName}`,objective:`Revert ${before.id} to tree ${target.id}`,allIfNothingStaged:true});return{before,target,reverted}}
async function git(cwd:string,args:string[]){return(await execFileAsync("git",args,{cwd,maxBuffer:16*1024*1024})).stdout.trim()}
export async function importGitRepository(source:string,destination?:string){const sourceRoot=resolve(source),root=destination?resolve(destination):sourceRoot;if(destination){await mkdir(dirname(root),{recursive:true});await execFileAsync("git",["clone","--no-hardlinks",sourceRoot,root])}await initializeRepository(root);const branches=(await git(root,["for-each-ref","--format=%(refname:short)","refs/heads/"])).split("\n").filter(Boolean);const original=(await git(root,["branch","--show-current"]))||branches[0]||"main";const commits=(await git(root,["rev-list","--reverse","--topo-order","--all"])).split("\n").filter(Boolean);const checkpointBySha=new Map<string,string>();for(const sha of commits){await git(root,["checkout","--force",sha]);const subject=await git(root,["show","-s","--format=%s",sha]);const author=await git(root,["show","-s","--format=%an <%ae>",sha]);const cp=await createCheckpoint(root,{friendlyName:subject||sha.slice(0,12),objective:`Imported from Git ${sha}`,actorIds:[author],allIfNothingStaged:true});checkpointBySha.set(sha,cp.id)}for(const branch of branches){const sha=await git(root,["rev-parse",branch]),cp=checkpointBySha.get(sha);if(!cp)continue;try{await createWorkstream(root,{name:branch,fromCheckpointId:cp})}catch{}}for(const tag of (await git(root,["tag","--list"])).split("\n").filter(Boolean)){const sha=await git(root,["rev-list","-n","1",tag]),cp=checkpointBySha.get(sha);if(cp)try{await createTag(root,tag,cp,`Imported Git tag ${tag}`)}catch{}}const target=(await listWorkstreams(root)).find(w=>w.name===original);if(target)await checkoutWorkstream(root,target.id);await git(root,["checkout","--force",original]);return{repository:await openRepository(root),branches:branches.length,commits:commits.length,tags:(await listTags(root)).length,checkpointBySha:Object.fromEntries(checkpointBySha)}}
