import { execFile } from "node:child_process";
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { promisify } from "node:util";
import { checkoutWorkstream, createCheckpoint, createWorkstream, digest, getActiveWorkstream, getCheckpoint, getSourceManifest, initializeRepository, listHistory, listWorkstreams, openRepository, repositoryStatus, restoreCheckpoint, stagePaths } from "./core.js";

const execFileAsync = promisify(execFile);
type Remote={name:string;url:string;fetch?:string;push?:string};
type RemoteConfig={version:1;remotes:Remote[]};
type Tag={version:1;name:string;checkpointId:string;message?:string;createdAt:string};
type NativeObject={objectId:string;digest:string;size:number;contentBase64:string};
type NativeBundle={version:1;protocol:"sessions-native";repository:any;state:any;refs:any[];checkpoints:any[];manifests:any[];objects:NativeObject[];sourceDigest?:string};
type NativeState={version:1;protocol:"sessions-native";repository:any;state:any;refs:any[];checkpoints:any[];manifests:any[];objects:Array<Omit<NativeObject,"contentBase64">>;sourceDigest?:string};
const internal=(root:string)=>join(root,".sessions");
const readJson=async<T>(p:string):Promise<T>=>JSON.parse(await readFile(p,"utf8"));
const writeJson=async(p:string,v:unknown)=>{await mkdir(dirname(p),{recursive:true});await writeFile(p,JSON.stringify(v,null,2)+"\n","utf8")};
const remoteFile=(root:string)=>join(internal(root),"remotes.json");
const tagDir=(root:string)=>join(internal(root),"refs","tags");
const stateFile=(root:string)=>join(internal(root),"state.json");
const checkpointDir=(root:string)=>join(internal(root),"checkpoints");
const workstreamDir=(root:string)=>join(internal(root),"refs","workstreams");
const manifestDir=(root:string)=>join(internal(root),"objects","manifests");
const objectFile=(root:string,objectId:string)=>{const hash=objectId.replace(/^obj_/,"");return join(internal(root),"objects","blobs",hash.slice(0,2),hash.slice(2))};
async function config(root:string):Promise<RemoteConfig>{try{return await readJson(remoteFile(root))}catch{return{version:1,remotes:[]}}}
export async function listRemotes(root:string){return(await config(root)).remotes}
export async function setRemote(root:string,name:string,url:string){await openRepository(root);const c=await config(root);const next={version:1 as const,remotes:[...c.remotes.filter(r=>r.name!==name),{name,url:url.replace(/\/$/,"")}]};await writeJson(remoteFile(root),next);return next.remotes.find(r=>r.name===name)!}
export async function removeRemote(root:string,name:string){const c=await config(root);await writeJson(remoteFile(root),{version:1,remotes:c.remotes.filter(r=>r.name!==name)})}
async function remote(root:string,name:string){const r=(await listRemotes(root)).find(x=>x.name===name);if(!r)throw new Error(`Unknown remote: ${name}`);return r}
function isHosted(url:string){return /^https?:\/\//.test(url)}
function hostedToken(){const token=process.env.SESSIONS_API_TOKEN?.trim();if(!token)throw new Error("SESSIONS_API_TOKEN is required for hosted Sessions transport");return token}
function repositoryCollection(url:string){const clean=url.replace(/\/$/,"");if(/\/api\/repositories$/.test(clean))return clean;if(/\/api\/repositories\/[^/]+$/.test(clean))return clean.replace(/\/[^/]+$/,"");return `${clean}/api/repositories`}
function repositoryEndpoint(url:string,repositoryId:string){const clean=url.replace(/\/$/,"");if(/\/api\/repositories\/[^/]+$/.test(clean))return clean;return `${repositoryCollection(clean)}/${encodeURIComponent(repositoryId)}`}
async function hostedRequest(url:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set("authorization",`Bearer ${hostedToken()}`);if(!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(url,{...init,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error??`Sessions remote HTTP ${response.status}`);return body}
async function hostedObjectUpload(endpoint:string,object:NativeObject,content:Buffer){const binary=Uint8Array.from(content).buffer;const response=await fetch(`${endpoint}/objects/${encodeURIComponent(object.objectId)}?digest=${encodeURIComponent(object.digest)}&size=${object.size}`,{method:"POST",headers:{authorization:`Bearer ${hostedToken()}`,"content-type":"application/octet-stream"},body:binary});const body=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(body?.error??`Sessions object upload HTTP ${response.status}`);return body}
export async function createNativeBundle(root:string):Promise<NativeBundle>{
  const repository=await openRepository(root),state=await readJson<any>(stateFile(root)),branches=await listWorkstreams(root),checkpoints=await listHistory(root),tags=await listTags(root);
  const manifestIds=[...new Set(checkpoints.map(c=>c.sourceManifestId))],manifests=await Promise.all(manifestIds.map(id=>getSourceManifest(root,id)));
  const objectEntries=new Map<string,{objectId:string;digest:string;size:number}>();for(const manifest of manifests)for(const entry of manifest.entries)objectEntries.set(entry.objectId,{objectId:entry.objectId,digest:entry.digest,size:entry.size});
  const objects:NativeObject[]=[];for(const object of objectEntries.values()){const content=await readFile(objectFile(root,object.objectId));if(digest(content)!==object.digest)throw new Error(`Sessions object integrity failed before push: ${object.objectId}`);objects.push({...object,contentBase64:content.toString("base64")});}
  const refs=[...branches.map(b=>({refType:"branch",name:b.name,checkpointId:b.headCheckpointId??null,metadata:{id:b.id,objective:b.objective,createdAt:b.createdAt,updatedAt:b.updatedAt}})),...tags.map(t=>({refType:"tag",name:t.name,checkpointId:t.checkpointId,metadata:{message:t.message,createdAt:t.createdAt}}))];
  return{version:1,protocol:"sessions-native",repository,state:{repository,state,branches,tags},refs,checkpoints,manifests,objects,sourceDigest:checkpoints[0]?.sourceDigest};
}
function metadata(bundle:NativeBundle){return{version:1,protocol:"sessions-native",state:bundle.state,refs:bundle.refs,checkpoints:bundle.checkpoints,manifests:bundle.manifests,sourceDigest:bundle.sourceDigest}}
function synchronizedHostedState(state:NativeState){
  const raw=state.state??{};
  const previousBranches=Array.isArray(raw.branches)?raw.branches:[];
  const previousTags=Array.isArray(raw.tags)?raw.tags:[];
  const branches=(state.refs??[]).filter(ref=>(ref.ref_type??ref.refType)==="branch").map(ref=>{const meta=ref.metadata??{};const previous=previousBranches.find((branch:any)=>branch.id===meta.id||branch.name===ref.name);const id=meta.id??previous?.id;if(!id)throw new Error(`Hosted Sessions branch lacks native workstream identity: ${ref.name}`);return{...previous,id,repositoryId:state.repository.id,name:ref.name,objective:meta.objective??previous?.objective,headCheckpointId:ref.checkpoint_id??ref.checkpointId??undefined,createdAt:meta.createdAt??previous?.createdAt??state.repository.created_at,updatedAt:meta.updatedAt??previous?.updatedAt??state.repository.updated_at};});
  const tags=(state.refs??[]).filter(ref=>(ref.ref_type??ref.refType)==="tag").map(ref=>{const meta=ref.metadata??{};const previous=previousTags.find((tag:any)=>tag.name===ref.name);return{version:1,name:ref.name,checkpointId:ref.checkpoint_id??ref.checkpointId,message:meta.message??previous?.message,createdAt:meta.createdAt??previous?.createdAt??state.repository.updated_at};});
  return{...raw,repository:raw.repository??state.repository,branches,tags};
}
async function downloadBundle(endpoint:string):Promise<NativeBundle>{const state=await hostedRequest(`${endpoint}/state`) as NativeState;const objects:NativeObject[]=[];for(const descriptor of state.objects??[]){const object=await hostedRequest(`${endpoint}/objects/${encodeURIComponent(descriptor.objectId)}`) as NativeObject;if(object.digest!==descriptor.digest||Number(object.size)!==Number(descriptor.size))throw new Error(`Sessions object descriptor mismatch: ${descriptor.objectId}`);const content=Buffer.from(object.contentBase64,"base64");if(content.length!==Number(object.size)||digest(content)!==object.digest)throw new Error(`Sessions object integrity failed during download: ${object.objectId}`);objects.push(object);}return{version:1,protocol:"sessions-native",repository:state.repository,state:synchronizedHostedState(state),refs:state.refs,checkpoints:state.checkpoints,manifests:state.manifests,objects,sourceDigest:state.sourceDigest};}
async function uploadBundle(endpoint:string,bundle:NativeBundle){const descriptors=bundle.objects.map(({objectId,digest,size})=>({objectId,digest,size}));for(let offset=0;offset<descriptors.length;offset+=1000){const batch=descriptors.slice(offset,offset+1000);const plan=await hostedRequest(`${endpoint}/objects/plan`,{method:"POST",body:JSON.stringify({objects:batch})}) as {missing:string[]};const missing=new Set(plan.missing??[]);for(const object of bundle.objects){if(!missing.has(object.objectId))continue;const content=Buffer.from(object.contentBase64,"base64");await hostedObjectUpload(endpoint,object,content);missing.delete(object.objectId);if(!missing.size)break;}}await hostedRequest(`${endpoint}/state`,{method:"POST",body:JSON.stringify(metadata(bundle))});}
async function applyNativeBundle(root:string,bundle:NativeBundle){if(bundle.protocol!=="sessions-native"||bundle.version!==1)throw new Error("Unsupported Sessions repository protocol");const base=internal(root);await rm(base,{recursive:true,force:true});for(const p of [workstreamDir(root),checkpointDir(root),tagDir(root),manifestDir(root),join(base,"objects","blobs")])await mkdir(p,{recursive:true});const repository=bundle.state?.repository??bundle.repository,state=bundle.state?.state??bundle.state;await writeJson(join(base,"repository.json"),repository);await writeJson(stateFile(root),state);for(const branch of bundle.state?.branches??[])await writeJson(join(workstreamDir(root),`${branch.id}.json`),branch);for(const tag of bundle.state?.tags??[])await writeJson(join(tagDir(root),`${encodeURIComponent(tag.name)}.json`),tag);for(const checkpoint of bundle.checkpoints??[])await writeJson(join(checkpointDir(root),`${checkpoint.id}.json`),checkpoint);for(const manifest of bundle.manifests??[])await writeJson(join(manifestDir(root),`${manifest.id}.json`),manifest);for(const object of bundle.objects??[]){const content=Buffer.from(object.contentBase64,"base64");if(content.byteLength!==Number(object.size)||digest(content)!==object.digest)throw new Error(`Sessions object integrity failed during transfer: ${object.objectId}`);const path=objectFile(root,object.objectId);await mkdir(dirname(path),{recursive:true});await writeFile(path,content);}await materializeHead(root);}
async function materializeHead(root:string){const active=await getActiveWorkstream(root);if(active.headCheckpointId)await restoreCheckpoint(root,active.headCheckpointId)}
export async function cloneRepository(source:string,destination:string){const dest=resolve(destination);await mkdir(dest,{recursive:true});if(isHosted(source)){const match=source.replace(/\/$/,"").match(/\/api\/repositories\/([^/]+)$/);if(!match)throw new Error("Hosted clone URL must identify a Sessions repository, e.g. https://host/api/repositories/repo_id");const bundle=await downloadBundle(repositoryEndpoint(source,decodeURIComponent(match[1])));await applyNativeBundle(dest,bundle);return openRepository(dest);}const src=resolve(source);await cp(join(src,".sessions"),join(dest,".sessions"),{recursive:true,force:true});await materializeHead(dest);return openRepository(dest);}
export async function fetchRemote(root:string,name="origin"){const r=await remote(root,name),url=r.fetch??r.url,repository=await openRepository(root);if(isHosted(url)){const endpoint=repositoryEndpoint(url,repository.id),bundle=await downloadBundle(endpoint),incoming=join(internal(root),"remotes",name,"bundle.json");await writeJson(incoming,bundle);return{remote:name,fetchedAt:new Date().toISOString(),path:incoming,protocol:"sessions-native"};}const source=resolve(url),incoming=join(internal(root),"remotes",name);await rm(incoming,{recursive:true,force:true});await cp(join(source,".sessions"),incoming,{recursive:true,force:true});return{remote:name,fetchedAt:new Date().toISOString(),path:incoming,protocol:"sessions-native-local"};}
export async function pushRemote(root:string,name="origin"){const r=await remote(root,name),url=r.push??r.url;if(isHosted(url)){const bundle=await createNativeBundle(root),collection=repositoryCollection(url),endpoint=repositoryEndpoint(url,bundle.repository.id);await hostedRequest(collection,{method:"POST",body:JSON.stringify({id:bundle.repository.id,name:bundle.repository.name,defaultBranchId:bundle.repository.defaultWorkstreamId,sourceDigest:bundle.sourceDigest})});await uploadBundle(endpoint,bundle);return{remote:name,pushedAt:new Date().toISOString(),protocol:"sessions-native",objects:bundle.objects.length};}const destination=resolve(url);await mkdir(destination,{recursive:true});await cp(join(root,".sessions"),join(destination,".sessions"),{recursive:true,force:true});return{remote:name,pushedAt:new Date().toISOString(),protocol:"sessions-native-local"};}
export async function pullRemote(root:string,name="origin"){const r=await remote(root,name),status=await repositoryStatus(root);if(!status.clean)throw new Error("Cannot pull with local staged or unstaged changes");const savedRemotes=await config(root),url=r.fetch??r.url,local=await openRepository(root);if(isHosted(url)){const endpoint=repositoryEndpoint(url,local.id),bundle=await downloadBundle(endpoint);if(local.id!==bundle.repository.id)throw new Error("Remote repository identity does not match local Sessions repository");await applyNativeBundle(root,bundle);await writeJson(remoteFile(root),savedRemotes);return{remote:name,pulledAt:new Date().toISOString(),headCheckpointId:(await getActiveWorkstream(root)).headCheckpointId,protocol:"sessions-native"};}const source=resolve(url),upstream=await openRepository(source);if(local.id!==upstream.id)throw new Error("Remote repository identity does not match local Sessions repository");await cp(join(source,".sessions"),join(root,".sessions"),{recursive:true,force:true});await writeJson(remoteFile(root),savedRemotes);await materializeHead(root);return{remote:name,pulledAt:new Date().toISOString(),headCheckpointId:(await getActiveWorkstream(root)).headCheckpointId,protocol:"sessions-native-local"};}
export async function createTag(root:string,name:string,checkpointRef?:string,message?:string){const active=await getActiveWorkstream(root);const checkpoint=checkpointRef?await getCheckpoint(root,checkpointRef):active.headCheckpointId?await getCheckpoint(root,active.headCheckpointId):undefined;if(!checkpoint)throw new Error("Cannot tag repository without a checkpoint");const p=join(tagDir(root),`${encodeURIComponent(name)}.json`);try{await stat(p);throw new Error(`Tag already exists: ${name}`)}catch(e:any){if(e?.code!=="ENOENT")throw e}const tag:Tag={version:1,name,checkpointId:checkpoint.id,message,createdAt:new Date().toISOString()};await writeJson(p,tag);return tag}
export async function listTags(root:string):Promise<Tag[]>{try{return await Promise.all((await readdir(tagDir(root))).filter(x=>x.endsWith(".json")).map(x=>readJson<Tag>(join(tagDir(root),x))))}catch{return[]}}
export async function deleteTag(root:string,name:string){await rm(join(tagDir(root),`${encodeURIComponent(name)}.json`),{force:true})}
export async function revertCheckpoint(root:string,reference:string,name?:string){const status=await repositoryStatus(root);if(!status.clean)throw new Error("Cannot revert with local staged or unstaged changes");const active=await getActiveWorkstream(root);if(!active.headCheckpointId)throw new Error("Cannot revert without a current checkpoint");const before=await getCheckpoint(root,active.headCheckpointId),target=await getCheckpoint(root,reference);await restoreCheckpoint(root,target.id);await stagePaths(root,["."]);const reverted=await createCheckpoint(root,{friendlyName:name??`Revert ${target.friendlyName}`,objective:`Revert ${before.id} to tree ${target.id}`,allIfNothingStaged:true});return{before,target,reverted}}

// Legacy migration adapter only. Git is never used by Sessions-native repositories, remotes, object transfer, push, pull, fetch, clone, commits, branches, tags, verification, or recovery.
async function git(cwd:string,args:string[]){return(await execFileAsync("git",args,{cwd,maxBuffer:16*1024*1024})).stdout.trim()}
export async function importGitRepository(source:string,destination?:string){const sourceRoot=resolve(source),root=destination?resolve(destination):sourceRoot;if(destination){await mkdir(dirname(root),{recursive:true});await execFileAsync("git",["clone","--no-hardlinks",sourceRoot,root])}await initializeRepository(root);const branches=(await git(root,["for-each-ref","--format=%(refname:short)","refs/heads/"])).split("\n").filter(Boolean);const original=(await git(root,["branch","--show-current"]))||branches[0]||"main";const commits=(await git(root,["rev-list","--reverse","--topo-order","--all"])).split("\n").filter(Boolean);const checkpointBySha=new Map<string,string>();for(const sha of commits){await git(root,["checkout","--force",sha]);const subject=await git(root,["show","-s","--format=%s",sha]);const author=await git(root,["show","-s","--format=%an <%ae>",sha]);const cp=await createCheckpoint(root,{friendlyName:subject||sha.slice(0,12),objective:`Imported from legacy Git ${sha}`,actorIds:[author],allIfNothingStaged:true});checkpointBySha.set(sha,cp.id)}for(const branch of branches){const sha=await git(root,["rev-parse",branch]),cp=checkpointBySha.get(sha);if(!cp)continue;try{await createWorkstream(root,{name:branch,fromCheckpointId:cp})}catch{}}for(const tag of (await git(root,["tag","--list"])).split("\n").filter(Boolean)){const sha=await git(root,["rev-list","-n","1",tag]),cp=checkpointBySha.get(sha);if(cp)try{await createTag(root,tag,cp,`Imported legacy tag ${tag}`)}catch{}}const target=(await listWorkstreams(root)).find(w=>w.name===original);if(target)await checkoutWorkstream(root,target.id);await git(root,["checkout","--force",original]);return{repository:await openRepository(root),branches:branches.length,commits:commits.length,tags:(await listTags(root)).length,checkpointBySha:Object.fromEntries(checkpointBySha)}}
