"use client";
import { useEffect,useMemo,useState } from "react";

type Ref={ref_type:string;name:string;checkpoint_id?:string|null};
type Checkpoint={id:string;sourceManifestId?:string;sourceDigest?:string};
type Entry={path:string;objectId:string;digest:string;size:number};
type Manifest={id:string;entries:Entry[]};
type State={refs:Ref[];checkpoints:Checkpoint[];manifests:Manifest[]};
type Change={path:string;kind:"added"|"modified"|"deleted";before?:Entry;after?:Entry};
type DiffLine={kind:"same"|"add"|"del";before?:number;after?:number;text:string};

export function PullRequestDiff({repositoryId,baseBranch,headBranch,headCommitId}:{repositoryId:string;baseBranch:string;headBranch:string;headCommitId:string}){
 const[changes,setChanges]=useState<Change[]>([]),[contents,setContents]=useState<Record<string,{before?:Uint8Array;after?:Uint8Array}>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[expanded,setExpanded]=useState<Record<string,boolean>>({});
 const token=typeof window!=="undefined"?localStorage.getItem("sessions_api_token"):null,api=typeof window!=="undefined"?(process.env.NEXT_PUBLIC_SESSIONS_API_URL||location.origin):"";
 useEffect(()=>{if(!token){setError("Sign in to load changed files.");setLoading(false);return;}const headers={authorization:`Bearer ${token}`};const get=async(path:string)=>{const r=await fetch(`${api}${path}`,{headers,cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??`HTTP ${r.status}`);return b;};(async()=>{const state=await get(`/api/repositories/${encodeURIComponent(repositoryId)}/state`) as State;const baseRef=state.refs.find(r=>r.ref_type==="branch"&&r.name===baseBranch),headRef=state.refs.find(r=>r.ref_type==="branch"&&r.name===headBranch);const baseId=baseRef?.checkpoint_id??null,headId=headCommitId||headRef?.checkpoint_id??null;if(!headId)throw new Error("Pull request head commit is unavailable.");const byId=new Map(state.checkpoints.map(c=>[c.id,c]));const byManifest=new Map(state.manifests.map(m=>[m.id,m]));const baseCp=baseId?byId.get(baseId):undefined,headCp=byId.get(headId);if(!headCp)throw new Error("Pull request head commit is not present in native repository state.");const baseManifest=baseCp?.sourceManifestId?byManifest.get(baseCp.sourceManifestId):undefined,headManifest=headCp.sourceManifestId?byManifest.get(headCp.sourceManifestId):undefined;if(!headManifest)throw new Error("Pull request head manifest is unavailable.");const before=new Map((baseManifest?.entries??[]).map(e=>[e.path,e])),after=new Map((headManifest.entries??[]).map(e=>[e.path,e])),paths=[...new Set([...before.keys(),...after.keys()])].sort(),next:Change[]=[];for(const path of paths){const a=before.get(path),b=after.get(path);if(!a&&b)next.push({path,kind:"added",after:b});else if(a&&!b)next.push({path,kind:"deleted",before:a});else if(a&&b&&a.digest!==b.digest)next.push({path,kind:"modified",before:a,after:b});}setChanges(next);const bytes:Record<string,{before?:Uint8Array;after?:Uint8Array}>={};for(const change of next){const item:{before?:Uint8Array;after?:Uint8Array}={};for(const side of ["before","after"] as const){const entry=change[side];if(!entry)continue;const obj=await get(`/api/repositories/${encodeURIComponent(repositoryId)}/objects/${encodeURIComponent(entry.objectId)}`);item[side]=Uint8Array.from(atob(obj.contentBase64),c=>c.charCodeAt(0));}bytes[change.path]=item;}setContents(bytes);setExpanded(Object.fromEntries(next.map(c=>[c.path,true])));})().catch(e=>setError(e instanceof Error?e.message:"Could not compute native diff.")).finally(()=>setLoading(false));},[api,baseBranch,headBranch,headCommitId,repositoryId,token]);
 const totals=useMemo(()=>changes.reduce((a,c)=>{a[c.kind]++;return a},{added:0,modified:0,deleted:0} as Record<Change["kind"],number>),[changes]);
 if(loading)return <section className="workspace-panel" style={{padding:22,marginBottom:16}}><strong>Computing native changed files…</strong><p style={{color:"var(--muted)"}}>Comparing Sessions manifests and verified objects.</p></section>;
 return <section className="workspace-panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Changed files</h2><p>{changes.length} changed · {totals.added} added · {totals.modified} modified · {totals.deleted} deleted</p></div></div>{error?<div className="sessions-empty"><strong>Diff unavailable.</strong>{error}</div>:changes.length===0?<div className="sessions-empty"><strong>No file changes.</strong>The base and head manifests contain identical source digests.</div>:<div>{changes.map(change=><FileDiff key={change.path} change={change} data={contents[change.path]??{}} expanded={expanded[change.path]!==false} toggle={()=>setExpanded(v=>({...v,[change.path]:!v[change.path]}))}/>)}</div>}</section>;
}

function FileDiff({change,data,expanded,toggle}:{change:Change;data:{before?:Uint8Array;after?:Uint8Array};expanded:boolean;toggle:()=>void}){const before=data.before??new Uint8Array(),after=data.after??new Uint8Array(),binary=isBinary(before)||isBinary(after),lines=binary?[]:diffLines(decode(before),decode(after));const additions=lines.filter(l=>l.kind==="add").length,deletions=lines.filter(l=>l.kind==="del").length;return <div style={{borderTop:"1px solid var(--border-soft)"}}><button onClick={toggle} style={{width:"100%",border:0,background:"transparent",color:"inherit",padding:"13px 18px",display:"grid",gridTemplateColumns:"34px 1fr auto",alignItems:"center",textAlign:"left",cursor:"pointer"}}><span className="feed-symbol">{change.kind==="added"?"+":change.kind==="deleted"?"−":"±"}</span><span className="feed-copy"><strong>{change.path}</strong><span>{change.kind} · {change.before?.digest.slice(0,10)??"∅"} → {change.after?.digest.slice(0,10)??"∅"}</span></span><span style={{fontFamily:"monospace",fontSize:12}}>+{additions} −{deletions}</span></button>{expanded?<div>{binary?<div className="sessions-empty"><strong>Binary change.</strong>Exact object digests and sizes are recorded, but binary bytes are not rendered as text.</div>:<pre style={{margin:0,overflow:"auto",maxHeight:620,background:"#090d13",fontSize:12,lineHeight:1.55}}>{lines.map((line,i)=><span key={i} style={{display:"grid",gridTemplateColumns:"54px 54px 20px minmax(0,1fr)",padding:"0 12px",background:line.kind==="add"?"rgba(46,160,67,.10)":line.kind==="del"?"rgba(248,81,73,.10)":"transparent"}}><span style={{color:"var(--muted-2)",userSelect:"none"}}>{line.before??""}</span><span style={{color:"var(--muted-2)",userSelect:"none"}}>{line.after??""}</span><span style={{userSelect:"none"}}>{line.kind==="add"?"+":line.kind==="del"?"-":" "}</span><span>{line.text||" "}</span></span>)}</pre>}</div>:null}</div>}
function decode(bytes:Uint8Array){return new TextDecoder().decode(bytes)}
function isBinary(bytes:Uint8Array){for(let i=0;i<Math.min(bytes.length,8192);i++)if(bytes[i]===0)return true;return false}
function diffLines(before:string,after:string):DiffLine[]{const a=before.split("\n"),b=after.split("\n"),n=a.length,m=b.length;if(n*m>4_000_000)return coarseDiff(a,b);const dp=Array.from({length:n+1},()=>new Uint32Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);const out:DiffLine[]=[];let i=0,j=0,bi=1,aj=1;while(i<n&&j<m){if(a[i]===b[j]){out.push({kind:"same",before:bi++,after:aj++,text:a[i++]});j++;}else if(dp[i+1][j]>=dp[i][j+1])out.push({kind:"del",before:bi++,text:a[i++]});else out.push({kind:"add",after:aj++,text:b[j++]});}while(i<n)out.push({kind:"del",before:bi++,text:a[i++]});while(j<m)out.push({kind:"add",after:aj++,text:b[j++]});return out}
function coarseDiff(a:string[],b:string[]):DiffLine[]{let prefix=0;while(prefix<a.length&&prefix<b.length&&a[prefix]===b[prefix])prefix++;let suffix=0;while(suffix<a.length-prefix&&suffix<b.length-prefix&&a[a.length-1-suffix]===b[b.length-1-suffix])suffix++;const out:DiffLine[]=[];for(let i=0;i<prefix;i++)out.push({kind:"same",before:i+1,after:i+1,text:a[i]});for(let i=prefix;i<a.length-suffix;i++)out.push({kind:"del",before:i+1,text:a[i]});for(let j=prefix;j<b.length-suffix;j++)out.push({kind:"add",after:j+1,text:b[j]});for(let k=suffix;k>0;k--){const ai=a.length-k,bi=b.length-k;out.push({kind:"same",before:ai+1,after:bi+1,text:a[ai]});}return out}
