import http from "node:http";
import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { Pool, type PoolClient } from "pg";

const scrypt = promisify(scryptCallback);
const port = Number(process.env.AUTH_PORT ?? 4200);
const databaseUrl = process.env.DATABASE_URL ?? "postgresql://sessions:sessions@localhost:5432/sessions";
const maxBody = Number(process.env.SESSIONS_MAX_BODY_BYTES ?? 1_048_576);
const rateLimit = Number(process.env.SESSIONS_AUTH_RATE_LIMIT ?? 20);
const pool = new Pool({ connectionString: databaseUrl, max: Number(process.env.SESSIONS_AUTH_DB_POOL_MAX ?? 10) });
const attempts = new Map<string, { count: number; resetAt: number }>();

class HttpError extends Error { constructor(public readonly status: number, message: string) { super(message); } }
type PlanKey = "developer"|"team"|"business"|"enterprise";
type Identity={workspaceId:string;principalId:string;role:string};
const planLimits: Record<PlanKey,{repositories:number|null;runnerSeconds:number|null;storageBytes:number|null;retainedEventBytes:number|null}> = {
  developer:{repositories:10,runnerSeconds:10_000,storageBytes:10*1024**3,retainedEventBytes:5*1024**3},
  team:{repositories:100,runnerSeconds:100_000,storageBytes:100*1024**3,retainedEventBytes:50*1024**3},
  business:{repositories:1000,runnerSeconds:1_000_000,storageBytes:1024*1024**3,retainedEventBytes:500*1024**3},
  enterprise:{repositories:null,runnerSeconds:null,storageBytes:null,retainedEventBytes:null},
};

function send(res: http.ServerResponse, status: number, body: unknown) { res.writeHead(status, { "content-type": "application/json", "cache-control": "no-store" }); res.end(JSON.stringify(body)); }
async function jsonBody(req: http.IncomingMessage) { const chunks: Buffer[]=[];let size=0;for await(const chunk of req){const buffer=Buffer.from(chunk);size+=buffer.length;if(size>maxBody)throw new HttpError(413,"request body too large");chunks.push(buffer);}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new HttpError(400,"invalid JSON body");} }
function clientKey(req: http.IncomingMessage) { return String(req.headers["x-forwarded-for"] ?? req.socket.remoteAddress ?? "unknown").split(",")[0].trim(); }
function enforceRateLimit(req: http.IncomingMessage) { const key=clientKey(req),now=Date.now(),prior=attempts.get(key),bucket=!prior||prior.resetAt<=now?{count:0,resetAt:now+60_000}:prior;bucket.count+=1;attempts.set(key,bucket);if(bucket.count>rateLimit)throw new HttpError(429,"too many authentication attempts; try again shortly"); }
function normalizeEmail(value: unknown) { return String(value ?? "").trim().toLowerCase(); }
function validateEmail(email:string){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpError(400,"valid email is required");}
function validatePassword(password: string) { if (password.length < 12 || password.length > 256) throw new HttpError(400, "password must be between 12 and 256 characters"); }
function validatePlan(plan: unknown):PlanKey { const value=String(plan??"developer") as PlanKey;if(!/^(developer|team|business|enterprise)$/.test(value))throw new HttpError(400,"invalid paid plan");return value; }
function validateRole(value:unknown){const role=String(value??"member");if(!["admin","member","viewer"].includes(role))throw new HttpError(400,"invalid workspace role");return role;}
function hashToken(token: string) { return createHash("sha256").update(token).digest("hex"); }
async function passwordHash(password: string, salt: string) { return (await scrypt(password, salt, 64) as Buffer).toString("hex"); }
async function verifyPassword(password: string, salt: string, expected: string) { const actual=Buffer.from(await passwordHash(password,salt),"hex"),target=Buffer.from(expected,"hex");return actual.length===target.length&&timingSafeEqual(actual,target); }
function ids() { const id=()=>randomUUID();return{org:`org_${id()}`,workspace:`workspace_${id()}`,principal:`principal_${id()}`,credential:`credential_${id()}`,billing:`billing_${id()}`}; }
function issueToken() { return `sess_${randomBytes(32).toString("hex")}`; }
const ownerScopes=["sessions:read","sessions:write","sessions:verify","sessions:rollback","metrics:read","billing:read","billing:write","account:export"];
const memberScopes=["sessions:read","sessions:write","sessions:verify"];
const viewerScopes=["sessions:read"];
function scopesFor(role:string){return role==="viewer"?viewerScopes:role==="member"?memberScopes:ownerScopes;}
async function createCredential(db: PoolClient, workspaceId: string, principalId: string, role="owner") { const token=issueToken();await db.query("insert into api_credentials(id,workspace_id,principal_id,token_hash,scopes) values($1,$2,$3,$4,$5)",[`credential_${randomUUID()}`,workspaceId,principalId,hashToken(token),scopesFor(role)]);return token; }
async function authenticate(req:http.IncomingMessage):Promise<Identity>{const auth=req.headers.authorization;if(!auth?.startsWith("Bearer "))throw new HttpError(401,"bearer token required");const r=await pool.query(`select c.workspace_id,c.principal_id,m.role from api_credentials c join principals p on p.id=c.principal_id join workspace_memberships m on m.workspace_id=c.workspace_id and m.principal_id=c.principal_id where c.token_hash=$1 and c.status='active' and p.status='active' and (c.expires_at is null or c.expires_at>now())`,[hashToken(auth.slice(7).trim())]);if(!r.rowCount)throw new HttpError(401,"invalid or expired credential");return{workspaceId:r.rows[0].workspace_id,principalId:r.rows[0].principal_id,role:r.rows[0].role};}
function requireAdmin(identity:Identity){if(!["owner","admin"].includes(identity.role))throw new HttpError(403,"owner or admin role required");}

async function signup(body:any) {
  const email=String(body.email??"").trim(),normalized=normalizeEmail(email),password=String(body.password??""),displayName=String(body.displayName??"").trim(),workspaceName=String(body.workspaceName??"").trim(),plan=validatePlan(body.planKey),limits=planLimits[plan];
  validateEmail(normalized);if(displayName.length<2||displayName.length>120)throw new HttpError(400,"display name is required");if(workspaceName.length<2||workspaceName.length>120)throw new HttpError(400,"workspace name is required");validatePassword(password);
  const salt=randomBytes(16).toString("hex"),digest=await passwordHash(password,salt),id=ids(),client=await pool.connect();
  try {
    await client.query("begin");
    if((await client.query("select 1 from hosted_auth_accounts where normalized_email=$1",[normalized])).rowCount)throw new HttpError(409,"an account already exists for this email");
    await client.query("insert into organizations(id,name) values($1,$2)",[id.org,workspaceName]);
    await client.query("insert into workspaces(id,organization_id,name) values($1,$2,$3)",[id.workspace,id.org,workspaceName]);
    await client.query("insert into principals(id,kind,display_name,email) values($1,'human',$2,$3)",[id.principal,displayName,email]);
    await client.query("insert into workspace_memberships(workspace_id,principal_id,role) values($1,$2,'owner')",[id.workspace,id.principal]);
    await client.query("insert into hosted_auth_accounts(principal_id,email,normalized_email,password_salt,password_hash) values($1,$2,$3,$4,$5)",[id.principal,email,normalized,salt,digest]);
    await client.query("insert into billing_accounts(id,workspace_id,plan_key,status,billing_email,payment_state) values($1,$2,$3,'pending',$4,'pending')",[id.billing,id.workspace,plan,email]);
    await client.query("insert into workspace_entitlements(workspace_id,plan_key,status,source,reason) values($1,$2,'suspended','internal','awaiting_payment')",[id.workspace,plan]);
    await client.query("insert into workspace_limits(workspace_id,hosted_repository_limit,runner_seconds_monthly_limit,storage_bytes_limit,retained_event_bytes_limit) values($1,$2,$3,$4,$5)",[id.workspace,limits.repositories,limits.runnerSeconds,limits.storageBytes,limits.retainedEventBytes]);
    await client.query("insert into product_events(id,workspace_id,principal_id,event_name,properties) values($1,$2,$3,'self_service_signup',$4)",[`product_${randomUUID()}`,id.workspace,id.principal,JSON.stringify({plan,limits})]);
    const token=await createCredential(client,id.workspace,id.principal);await client.query("commit");
    return{token,workspaceId:id.workspace,principalId:id.principal,planKey:plan,entitlementStatus:"suspended",limits};
  } catch(error:any){await client.query("rollback");if(error?.code==="23505")throw new HttpError(409,"an account already exists for this email");throw error;}finally{client.release();}
}

async function login(body:any) {
  const normalized=normalizeEmail(body.email),password=String(body.password??"");validatePassword(password);
  const result=await pool.query(`select a.*,p.status as principal_status,m.workspace_id,m.role from hosted_auth_accounts a join principals p on p.id=a.principal_id join workspace_memberships m on m.principal_id=a.principal_id where a.normalized_email=$1 order by case m.role when 'owner' then 0 when 'admin' then 1 else 2 end,m.created_at limit 1`,[normalized]);
  if(!result.rowCount)throw new HttpError(401,"invalid email or password");const account=result.rows[0];if(account.principal_status!=="active")throw new HttpError(403,"account is not active");if(account.locked_until&&new Date(account.locked_until).getTime()>Date.now())throw new HttpError(429,"account temporarily locked");
  if(!(await verifyPassword(password,account.password_salt,account.password_hash))){const failures=Number(account.failed_attempts??0)+1;await pool.query("update hosted_auth_accounts set failed_attempts=$2,locked_until=case when $2>=8 then now()+interval '15 minutes' else null end,updated_at=now() where principal_id=$1",[account.principal_id,failures]);throw new HttpError(401,"invalid email or password");}
  const client=await pool.connect();try{await client.query("begin");const token=await createCredential(client,account.workspace_id,account.principal_id,account.role);await client.query("update hosted_auth_accounts set failed_attempts=0,locked_until=null,last_login_at=now(),updated_at=now() where principal_id=$1",[account.principal_id]);await client.query("commit");return{token,workspaceId:account.workspace_id,principalId:account.principal_id,role:account.role};}catch(error){await client.query("rollback");throw error;}finally{client.release();}
}

async function createInvitation(identity:Identity,body:any){requireAdmin(identity);const email=String(body.email??"").trim(),normalized=normalizeEmail(email),role=validateRole(body.role);validateEmail(normalized);if((await pool.query("select 1 from workspace_memberships m join principals p on p.id=m.principal_id where m.workspace_id=$1 and lower(p.email)=lower($2)",[identity.workspaceId,email])).rowCount)throw new HttpError(409,"user is already a workspace member");await pool.query("update workspace_invitations set status='revoked',updated_at=now() where workspace_id=$1 and normalized_email=$2 and status='pending'",[identity.workspaceId,normalized]);const raw=`invite_${randomBytes(32).toString("hex")}`,id=`invite_${randomUUID()}`;await pool.query("insert into workspace_invitations(id,workspace_id,normalized_email,email,role,token_hash,invited_by,expires_at) values($1,$2,$3,$4,$5,$6,$7,now()+interval '7 days')",[id,identity.workspaceId,normalized,email,role,hashToken(raw),identity.principalId]);return{id,email,role,inviteToken:raw,expiresInSeconds:604800};}
async function listWorkspace(identity:Identity){const [workspace,members,invitations]=await Promise.all([pool.query("select id,name,status,organization_id,created_at from workspaces where id=$1",[identity.workspaceId]),pool.query("select p.id,p.display_name,p.email,p.kind,p.status,m.role,m.created_at from workspace_memberships m join principals p on p.id=m.principal_id where m.workspace_id=$1 order by case m.role when 'owner' then 0 when 'admin' then 1 else 2 end,m.created_at",[identity.workspaceId]),pool.query("select id,email,role,status,expires_at,created_at from workspace_invitations where workspace_id=$1 order by created_at desc limit 100",[identity.workspaceId])]);return{workspace:workspace.rows[0],current:{principalId:identity.principalId,role:identity.role},members:members.rows,invitations:invitations.rows};}
async function removeMember(identity:Identity,principalId:string){requireAdmin(identity);if(principalId===identity.principalId)throw new HttpError(409,"cannot remove your own active membership");const target=await pool.query("select role from workspace_memberships where workspace_id=$1 and principal_id=$2",[identity.workspaceId,principalId]);if(!target.rowCount)throw new HttpError(404,"workspace member not found");if(target.rows[0].role==="owner")throw new HttpError(409,"owner membership cannot be removed by this operation");const client=await pool.connect();try{await client.query("begin");await client.query("delete from workspace_memberships where workspace_id=$1 and principal_id=$2",[identity.workspaceId,principalId]);await client.query("update api_credentials set status='revoked' where workspace_id=$1 and principal_id=$2",[identity.workspaceId,principalId]);await client.query("commit");return{removed:true,principalId};}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
async function updateMemberRole(identity:Identity,principalId:string,body:any){requireAdmin(identity);const role=validateRole(body.role);const target=await pool.query("select role from workspace_memberships where workspace_id=$1 and principal_id=$2",[identity.workspaceId,principalId]);if(!target.rowCount)throw new HttpError(404,"workspace member not found");if(target.rows[0].role==="owner")throw new HttpError(409,"owner role cannot be changed by this operation");await pool.query("update workspace_memberships set role=$3 where workspace_id=$1 and principal_id=$2",[identity.workspaceId,principalId,role]);await pool.query("update api_credentials set status='revoked' where workspace_id=$1 and principal_id=$2",[identity.workspaceId,principalId]);return{principalId,role,credentialsRevoked:true};}
async function acceptInvitation(body:any){const raw=String(body.inviteToken??""),password=String(body.password??""),displayName=String(body.displayName??"").trim();if(!raw)throw new HttpError(400,"inviteToken is required");validatePassword(password);const invite=(await pool.query("select * from workspace_invitations where token_hash=$1 and status='pending' and expires_at>now()",[hashToken(raw)])).rows[0];if(!invite)throw new HttpError(400,"invitation is invalid, expired, or already used");const existing=(await pool.query("select a.*,p.status from hosted_auth_accounts a join principals p on p.id=a.principal_id where a.normalized_email=$1",[invite.normalized_email])).rows[0];let principalId:string;const client=await pool.connect();try{await client.query("begin");if(existing){if(!(await verifyPassword(password,existing.password_salt,existing.password_hash)))throw new HttpError(401,"invalid password for invited account");principalId=existing.principal_id;}else{if(displayName.length<2||displayName.length>120)throw new HttpError(400,"display name is required for a new account");const salt=randomBytes(16).toString("hex"),digest=await passwordHash(password,salt);principalId=`principal_${randomUUID()}`;await client.query("insert into principals(id,kind,display_name,email) values($1,'human',$2,$3)",[principalId,displayName,invite.email]);await client.query("insert into hosted_auth_accounts(principal_id,email,normalized_email,password_salt,password_hash) values($1,$2,$3,$4,$5)",[principalId,invite.email,invite.normalized_email,salt,digest]);}await client.query("insert into workspace_memberships(workspace_id,principal_id,role) values($1,$2,$3) on conflict(workspace_id,principal_id) do update set role=excluded.role",[invite.workspace_id,principalId,invite.role]);await client.query("update workspace_invitations set status='accepted',accepted_by=$2,accepted_at=now(),updated_at=now() where id=$1",[invite.id,principalId]);const token=await createCredential(client,invite.workspace_id,principalId,invite.role);await client.query("commit");return{token,workspaceId:invite.workspace_id,principalId,role:invite.role};}catch(error){await client.query("rollback");throw error;}finally{client.release();}}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url??"/",`http://${req.headers.host??"localhost"}`);if(req.method==="GET"&&url.pathname==="/health"){await pool.query("select 1");return send(res,200,{ok:true,service:"sessions-auth"});}if(req.method==="POST"&&url.pathname==="/api/auth/signup"){enforceRateLimit(req);return send(res,201,await signup(await jsonBody(req)));}if(req.method==="POST"&&url.pathname==="/api/auth/login"){enforceRateLimit(req);return send(res,200,await login(await jsonBody(req)));}if(req.method==="POST"&&url.pathname==="/api/auth/invitations/accept"){enforceRateLimit(req);return send(res,200,await acceptInvitation(await jsonBody(req)));}const identity=await authenticate(req);if(req.method==="GET"&&url.pathname==="/api/auth/workspace")return send(res,200,await listWorkspace(identity));if(req.method==="POST"&&url.pathname==="/api/auth/workspace/invitations")return send(res,201,await createInvitation(identity,await jsonBody(req)));let match=url.pathname.match(/^\/api\/auth\/workspace\/members\/([^/]+)\/(role|remove)$/);if(match&&req.method==="POST"){const principalId=decodeURIComponent(match[1]);return send(res,200,match[2]==="role"?await updateMemberRole(identity,principalId,await jsonBody(req)):await removeMember(identity,principalId));}throw new HttpError(404,"not found");}catch(error){const status=error instanceof HttpError?error.status:500,message=error instanceof Error?error.message:"internal error";return send(res,status,{error:status>=500?"internal error":message});}});
server.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({level:"info",event:"auth.started",port})));async function shutdown(){server.close(async()=>{await pool.end();process.exit(0);});setTimeout(()=>process.exit(1),10_000).unref();}process.on("SIGTERM",()=>void shutdown());process.on("SIGINT",()=>void shutdown());
