import { randomUUID } from "node:crypto";
import type { IncomingMessage } from "node:http";
import type { Pool } from "pg";

type Identity={workspaceId:string;principalId:string;scopes:string[]};
type Context={pool:Pool;identity:Identity;req:IncomingMessage;url:URL;body:()=>Promise<any>;send:(status:number,body:unknown)=>void};
export class ReleaseGovernanceError extends Error{constructor(public status:number,message:string){super(message)}}
function hasScope(i:Identity,s:string){return i.scopes.includes("*")||i.scopes.includes(s)}
function scope(i:Identity,s:string){if(!hasScope(i,s)&&!hasScope(i,"sessions:write"))throw new ReleaseGovernanceError(403,`missing scope: ${s}`)}
async function repository(c:Context,id:string){const r=await c.pool.query("select id from hosted_repositories where id=$1 and workspace_id=$2",[id,c.identity.workspaceId]);if(!r.rowCount)throw new ReleaseGovernanceError(404,"repository not found")}
async function entitlement(c:Context){const r=await c.pool.query("select status from workspace_entitlements where workspace_id=$1",[c.identity.workspaceId]);if(r.rows[0]?.status!=="active")throw new ReleaseGovernanceError(402,"active Sessions entitlement required")}

export async function handleReleaseGovernance(c:Context):Promise<boolean>{
  let m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/environment-policies$/);
  if(m){const repositoryId=decodeURIComponent(m[1]);await repository(c,repositoryId);
    if(c.req.method==="GET"){scope(c.identity,"sessions:read");const r=await c.pool.query("select * from repository_environment_policies where workspace_id=$1 and repository_id=$2 order by environment",[c.identity.workspaceId,repositoryId]);c.send(200,r.rows);return true}
    if(c.req.method==="PUT"){scope(c.identity,"sessions:write");await entitlement(c);const b=await c.body();const environment=String(b.environment??"").trim();if(!environment||environment.length>128||!/^[A-Za-z0-9._:-]+$/.test(environment))throw new ReleaseGovernanceError(400,"valid environment is required");const approvals=Number(b.requiredApprovals??1),human=Number(b.requiredHumanApprovals??1);if(!Number.isInteger(approvals)||approvals<0||approvals>100)throw new ReleaseGovernanceError(400,"requiredApprovals must be 0 to 100");if(!Number.isInteger(human)||human<0||human>approvals)throw new ReleaseGovernanceError(400,"requiredHumanApprovals must be between 0 and requiredApprovals");const r=await c.pool.query(`insert into repository_environment_policies(workspace_id,repository_id,environment,require_release,require_verified_checkpoint,required_approvals,required_human_approvals,require_independent_approval,restrict_ai_deploy,require_attested_artifact,require_sbom,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) on conflict(repository_id,environment) do update set require_release=excluded.require_release,require_verified_checkpoint=excluded.require_verified_checkpoint,required_approvals=excluded.required_approvals,required_human_approvals=excluded.required_human_approvals,require_independent_approval=excluded.require_independent_approval,restrict_ai_deploy=excluded.restrict_ai_deploy,require_attested_artifact=excluded.require_attested_artifact,require_sbom=excluded.require_sbom,updated_at=now() returning *`,[c.identity.workspaceId,repositoryId,environment,b.requireRelease!==false,b.requireVerifiedCheckpoint!==false,approvals,human,b.requireIndependentApproval!==false,b.restrictAiDeploy===true,b.requireAttestedArtifact===true,b.requireSbom===true,c.identity.principalId]);await c.pool.query("insert into product_events(id,workspace_id,principal_id,event_name,repository_id,properties) values($1,$2,$3,'environment_policy_updated',$4,$5)",[`product_${randomUUID()}`,c.identity.workspaceId,c.identity.principalId,repositoryId,JSON.stringify({environment,approvals,human,requireAttestedArtifact:b.requireAttestedArtifact===true,requireSbom:b.requireSbom===true})]);c.send(200,r.rows[0]);return true}
  }
  m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/environment-policies\/([^/]+)$/);
  if(m&&c.req.method==="DELETE"){const repositoryId=decodeURIComponent(m[1]),environment=decodeURIComponent(m[2]);await repository(c,repositoryId);scope(c.identity,"sessions:write");await entitlement(c);const r=await c.pool.query("delete from repository_environment_policies where workspace_id=$1 and repository_id=$2 and environment=$3 returning environment",[c.identity.workspaceId,repositoryId,environment]);if(!r.rowCount)throw new ReleaseGovernanceError(404,"environment policy not found");c.send(200,{repositoryId,environment,deleted:true});return true}

  m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/deployments\/([^/]+)\/(approvals|status)$/);
  if(m){const repositoryId=decodeURIComponent(m[1]),deploymentId=decodeURIComponent(m[2]),action=m[3];await repository(c,repositoryId);const deployment=(await c.pool.query("select * from repository_deployments where id=$1 and workspace_id=$2 and repository_id=$3",[deploymentId,c.identity.workspaceId,repositoryId])).rows[0];if(!deployment)throw new ReleaseGovernanceError(404,"deployment not found");
    if(action==="approvals"&&c.req.method==="GET"){scope(c.identity,"sessions:read");const r=await c.pool.query("select a.*,p.kind reviewer_kind,p.display_name reviewer_name from deployment_approvals a join principals p on p.id=a.reviewer_principal_id where a.deployment_id=$1 order by a.created_at",[deploymentId]);c.send(200,r.rows);return true}
    if(action==="approvals"&&c.req.method==="POST"){scope(c.identity,"sessions:write");const b=await c.body();if(!["approved","rejected","dismissed"].includes(b.state))throw new ReleaseGovernanceError(400,"state must be approved, rejected or dismissed");const r=await c.pool.query(`insert into deployment_approvals(deployment_id,reviewer_principal_id,state,body) values($1,$2,$3,$4) on conflict(deployment_id,reviewer_principal_id) do update set state=excluded.state,body=excluded.body,updated_at=now() returning *`,[deploymentId,c.identity.principalId,b.state,b.body??""]);c.send(201,r.rows[0]);return true}
    if(action==="status"&&c.req.method==="POST"){scope(c.identity,"sessions:write");const b=await c.body();if(!["running","success","failure","rolled_back"].includes(b.status))throw new ReleaseGovernanceError(400,"invalid deployment status transition");const r=await c.pool.query("update repository_deployments set status=$4,evidence=evidence||$5::jsonb,completed_at=case when $4 in ('success','failure','rolled_back') then now() else completed_at end where id=$1 and workspace_id=$2 and repository_id=$3 returning *",[deploymentId,c.identity.workspaceId,repositoryId,b.status,JSON.stringify(b.evidence??{})]);c.send(200,r.rows[0]);return true}
  }
  return false
}
