import { randomUUID } from "node:crypto";
import type { IncomingMessage } from "node:http";
import type { Pool } from "pg";

type Identity={workspaceId:string;principalId:string;scopes:string[]};
type Context={pool:Pool;identity:Identity;req:IncomingMessage;url:URL;body:()=>Promise<any>;send:(status:number,body:unknown)=>void};
export class RepositoryLifecycleError extends Error{constructor(public status:number,message:string){super(message)}}
function hasScope(i:Identity,s:string){return i.scopes.includes("*")||i.scopes.includes(s)}
function scope(i:Identity,s:string){if(!hasScope(i,s)&&!hasScope(i,"sessions:write"))throw new RepositoryLifecycleError(403,`missing scope: ${s}`)}
async function repository(c:Context,id:string){const r=await c.pool.query("select * from hosted_repositories where id=$1 and workspace_id=$2",[id,c.identity.workspaceId]);if(!r.rowCount)throw new RepositoryLifecycleError(404,"repository not found");return r.rows[0]}
async function requireHumanAdmin(c:Context){const r=await c.pool.query(`select m.role,p.kind from workspace_memberships m join principals p on p.id=m.principal_id where m.workspace_id=$1 and m.principal_id=$2`,[c.identity.workspaceId,c.identity.principalId]);const row=r.rows[0];if(!row||row.kind!=="human"||!["owner","admin"].includes(row.role))throw new RepositoryLifecycleError(403,"repository lifecycle changes require a human workspace owner or admin")}
async function record(c:Context,repositoryId:string,action:string,previous:string,next:string,reason:string,metadata:Record<string,unknown>={}){await c.pool.query("insert into repository_lifecycle_events(id,workspace_id,repository_id,principal_id,action,previous_status,next_status,reason,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[randomUUID(),c.identity.workspaceId,repositoryId,c.identity.principalId,action,previous,next,reason,JSON.stringify(metadata)])}

async function purge(c:Context,repo:any,reason:string){if(repo.lifecycle_status!=="deletion_scheduled")throw new RepositoryLifecycleError(409,"repository is not scheduled for deletion");if(!repo.purge_after||new Date(repo.purge_after).getTime()>Date.now())throw new RepositoryLifecycleError(409,"repository retention window has not expired");const client=await c.pool.connect();try{await client.query("begin");await client.query("select set_config('sessions.lifecycle_purge','on',true)");await client.query("delete from repository_deployments where repository_id=$1",[repo.id]);await client.query("delete from repository_releases where repository_id=$1",[repo.id]);await client.query("delete from action_runs where repository_id=$1",[repo.id]);await client.query("delete from pull_requests where repository_id=$1",[repo.id]);await client.query("delete from repository_issues where repository_id=$1",[repo.id]);await client.query("delete from repository_action_secrets where repository_id=$1",[repo.id]);await client.query("delete from repository_action_workflows where repository_id=$1",[repo.id]);await client.query("delete from repository_branch_policies where repository_id=$1",[repo.id]);await client.query("delete from repository_environment_policies where repository_id=$1",[repo.id]);await client.query("delete from webhook_events where repository_id=$1",[repo.id]);await client.query("delete from repository_webhooks where repository_id=$1",[repo.id]);await client.query("delete from engineering_memory where repository_id=$1",[repo.id]);await client.query("delete from semantic_relationships where repository_id=$1",[repo.id]);await client.query("delete from sessions where repository_id=$1",[repo.id]);await client.query("insert into repository_lifecycle_events(id,workspace_id,repository_id,principal_id,action,previous_status,next_status,reason,metadata) values($1,$2,$3,$4,'purge',$5,'purged',$6,$7)",[randomUUID(),c.identity.workspaceId,repo.id,c.identity.principalId,repo.lifecycle_status,reason,JSON.stringify({purgedAt:new Date().toISOString()})]);await client.query("delete from hosted_repositories where id=$1 and workspace_id=$2",[repo.id,c.identity.workspaceId]);await client.query("commit");}catch(error){await client.query("rollback");throw error}finally{client.release()}}

export async function handleRepositoryLifecycle(c:Context):Promise<boolean>{
  const m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/lifecycle$/);if(!m)return false;
  const repositoryId=decodeURIComponent(m[1]);const repo=await repository(c,repositoryId);
  if(c.req.method==="GET"){scope(c.identity,"sessions:read");const events=await c.pool.query("select action,previous_status,next_status,reason,metadata,principal_id,occurred_at from repository_lifecycle_events where workspace_id=$1 and repository_id=$2 order by occurred_at desc limit 100",[c.identity.workspaceId,repositoryId]);c.send(200,{repository:repo,events:events.rows});return true}
  if(c.req.method!=="POST")throw new RepositoryLifecycleError(405,"method not allowed");scope(c.identity,"sessions:write");await requireHumanAdmin(c);const b=await c.body();const action=String(b.action??"");const reason=String(b.reason??"").trim();if(!reason)throw new RepositoryLifecycleError(400,"reason is required for repository lifecycle changes");
  if(action==="archive"){if(repo.lifecycle_status!=="active")throw new RepositoryLifecycleError(409,"only active repositories can be archived");const r=await c.pool.query("update hosted_repositories set lifecycle_status='archived',archived_at=now(),deletion_scheduled_at=null,purge_after=null,lifecycle_updated_by=$3,updated_at=now() where id=$1 and workspace_id=$2 returning *",[repositoryId,c.identity.workspaceId,c.identity.principalId]);await record(c,repositoryId,"archive",repo.lifecycle_status,"archived",reason);c.send(200,r.rows[0]);return true}
  if(action==="restore"){if(!["archived","deletion_scheduled"].includes(repo.lifecycle_status))throw new RepositoryLifecycleError(409,"repository is already active");const r=await c.pool.query("update hosted_repositories set lifecycle_status='active',archived_at=null,deletion_scheduled_at=null,purge_after=null,lifecycle_updated_by=$3,updated_at=now() where id=$1 and workspace_id=$2 returning *",[repositoryId,c.identity.workspaceId,c.identity.principalId]);await record(c,repositoryId,"restore",repo.lifecycle_status,"active",reason);c.send(200,r.rows[0]);return true}
  if(action==="schedule_delete"){if(repo.lifecycle_status==="deletion_scheduled")throw new RepositoryLifecycleError(409,"repository deletion is already scheduled");const days=Number(b.retentionDays??30);if(!Number.isInteger(days)||days<7||days>365)throw new RepositoryLifecycleError(400,"retentionDays must be an integer from 7 to 365");const r=await c.pool.query("update hosted_repositories set lifecycle_status='deletion_scheduled',archived_at=coalesce(archived_at,now()),deletion_scheduled_at=now(),purge_after=now()+($3::text||' days')::interval,lifecycle_updated_by=$4,updated_at=now() where id=$1 and workspace_id=$2 returning *",[repositoryId,c.identity.workspaceId,days,c.identity.principalId]);await record(c,repositoryId,"schedule_delete",repo.lifecycle_status,"deletion_scheduled",reason,{retentionDays:days});c.send(202,r.rows[0]);return true}
  if(action==="cancel_delete"){if(repo.lifecycle_status!=="deletion_scheduled")throw new RepositoryLifecycleError(409,"repository deletion is not scheduled");const r=await c.pool.query("update hosted_repositories set lifecycle_status='archived',deletion_scheduled_at=null,purge_after=null,lifecycle_updated_by=$3,updated_at=now() where id=$1 and workspace_id=$2 returning *",[repositoryId,c.identity.workspaceId,c.identity.principalId]);await record(c,repositoryId,"cancel_delete","deletion_scheduled","archived",reason);c.send(200,r.rows[0]);return true}
  if(action==="purge"){if(String(b.confirmRepositoryId??"")!==repositoryId)throw new RepositoryLifecycleError(400,"confirmRepositoryId must exactly match the repository id");await purge(c,repo,reason);c.send(200,{repositoryId,purged:true});return true}
  throw new RepositoryLifecycleError(400,"unknown lifecycle action")
}
