import { createHash, createPublicKey, randomUUID, verify } from "node:crypto";
import type { IncomingMessage } from "node:http";
import type { Pool } from "pg";

type Identity={workspaceId:string;principalId:string;scopes:string[]};
type Context={pool:Pool;identity:Identity;req:IncomingMessage;url:URL;body:()=>Promise<any>;send:(status:number,body:unknown)=>void};
export class SupplyChainError extends Error{constructor(public status:number,message:string){super(message)}}
function hasScope(i:Identity,s:string){return i.scopes.includes("*")||i.scopes.includes(s)}
function scope(i:Identity,s:string){if(!hasScope(i,s)&&!hasScope(i,"sessions:write"))throw new SupplyChainError(403,`missing scope: ${s}`)}
async function repository(c:Context,id:string){const r=await c.pool.query("select id,lifecycle_status from hosted_repositories where id=$1 and workspace_id=$2",[id,c.identity.workspaceId]);if(!r.rowCount)throw new SupplyChainError(404,"repository not found");return r.rows[0]}
function requireActiveRepository(r:any){if(r.lifecycle_status!=="active")throw new SupplyChainError(409,"repository is read-only")}
async function entitlement(c:Context){const r=await c.pool.query("select status from workspace_entitlements where workspace_id=$1",[c.identity.workspaceId]);if(r.rows[0]?.status!=="active")throw new SupplyChainError(402,"active Sessions entitlement required")}
function canonical(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;const object=value as Record<string,unknown>;return `{${Object.keys(object).sort().map(k=>`${JSON.stringify(k)}:${canonical(object[k])}`).join(",")}}`}
function ed25519Key(pem:string){let key;try{key=createPublicKey(pem)}catch{throw new SupplyChainError(400,"invalid public key")};if(key.asymmetricKeyType!=="ed25519")throw new SupplyChainError(400,"only Ed25519 signing keys are supported");return key}
function fingerprint(pem:string){const key=ed25519Key(pem);const der=key.export({type:"spki",format:"der"});return createHash("sha256").update(der).digest("hex")}
function bindStatement(statement:any,artifact:any,repositoryId:string){const digest=String(statement?.subject?.sha256??"").toLowerCase();const commitId=String(statement?.commitId??"");const statementRepository=String(statement?.repositoryId??"");const releaseId=String(statement?.releaseId??"");if(digest!==artifact.sha256)throw new SupplyChainError(400,"attestation subject digest does not match artifact");if(commitId!==artifact.commit_id)throw new SupplyChainError(400,"attestation commit does not match artifact");if(statementRepository!==repositoryId)throw new SupplyChainError(400,"attestation repository does not match artifact");if(artifact.release_id&&releaseId!==String(artifact.release_id))throw new SupplyChainError(400,"attestation release does not match artifact")}

export async function handleSupplyChain(c:Context):Promise<boolean>{
  let m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/signing-keys$/);
  if(m){const repositoryId=decodeURIComponent(m[1]);await repository(c,repositoryId);
    if(c.req.method==="GET"){scope(c.identity,"sessions:read");const r=await c.pool.query("select id,principal_id,algorithm,fingerprint_sha256,status,created_at,revoked_at from principal_signing_keys where workspace_id=$1 order by created_at desc",[c.identity.workspaceId]);c.send(200,r.rows);return true}
    if(c.req.method==="POST"){scope(c.identity,"sessions:write");await entitlement(c);const b=await c.body();const pem=String(b.publicKeyPem??"").trim();if(!pem)throw new SupplyChainError(400,"publicKeyPem is required");const fp=fingerprint(pem);const r=await c.pool.query(`insert into principal_signing_keys(workspace_id,principal_id,algorithm,public_key_pem,fingerprint_sha256) values($1,$2,'ed25519',$3,$4) on conflict(workspace_id,fingerprint_sha256) do update set status='active',revoked_at=null where principal_signing_keys.principal_id=excluded.principal_id returning id,principal_id,algorithm,fingerprint_sha256,status,created_at,revoked_at`,[c.identity.workspaceId,c.identity.principalId,pem,fp]);if(!r.rowCount)throw new SupplyChainError(409,"signing key is registered to another principal");c.send(201,r.rows[0]);return true}
  }
  m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/signing-keys\/([^/]+)$/);
  if(m&&c.req.method==="DELETE"){const repositoryId=decodeURIComponent(m[1]),keyId=decodeURIComponent(m[2]);await repository(c,repositoryId);scope(c.identity,"sessions:write");const r=await c.pool.query("update principal_signing_keys set status='revoked',revoked_at=now() where id=$1 and workspace_id=$2 and principal_id=$3 and status='active' returning id,fingerprint_sha256,status,revoked_at",[keyId,c.identity.workspaceId,c.identity.principalId]);if(!r.rowCount)throw new SupplyChainError(404,"active signing key not found for principal");c.send(200,r.rows[0]);return true}

  m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/artifacts$/);
  if(m){const repositoryId=decodeURIComponent(m[1]);const repositoryRecord=await repository(c,repositoryId);
    if(c.req.method==="GET"){scope(c.identity,"sessions:read");const r=await c.pool.query(`select a.*,coalesce((select count(*) from artifact_attestations at where at.artifact_id=a.id),0)::int attestation_count from repository_artifacts a where a.workspace_id=$1 and a.repository_id=$2 order by a.created_at desc limit 200`,[c.identity.workspaceId,repositoryId]);c.send(200,r.rows);return true}
    if(c.req.method==="POST"){scope(c.identity,"sessions:write");requireActiveRepository(repositoryRecord);await entitlement(c);const b=await c.body();const name=String(b.name??"").trim(),commitId=String(b.commitId??"").trim(),sha256=String(b.sha256??"").toLowerCase();if(!name||name.length>512)throw new SupplyChainError(400,"valid artifact name is required");if(!commitId)throw new SupplyChainError(400,"commitId is required");if(!/^[a-f0-9]{64}$/.test(sha256))throw new SupplyChainError(400,"sha256 must be a lowercase SHA-256 digest");const size=Number(b.sizeBytes);if(!Number.isSafeInteger(size)||size<0)throw new SupplyChainError(400,"sizeBytes must be a non-negative integer");const r=await c.pool.query(`insert into repository_artifacts(id,workspace_id,repository_id,commit_id,action_run_id,release_id,name,media_type,size_bytes,sha256,storage_key,sbom,metadata,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *`,[randomUUID(),c.identity.workspaceId,repositoryId,commitId,b.actionRunId??null,b.releaseId??null,name,b.mediaType??"application/octet-stream",size,sha256,b.storageKey??null,b.sbom??null,JSON.stringify(b.metadata??{}),c.identity.principalId]);c.send(201,r.rows[0]);return true}
  }
  m=c.url.pathname.match(/^\/api\/repositories\/([^/]+)\/artifacts\/([^/]+)\/attestations$/);
  if(m){const repositoryId=decodeURIComponent(m[1]),artifactId=decodeURIComponent(m[2]);const repositoryRecord=await repository(c,repositoryId);const artifact=(await c.pool.query("select * from repository_artifacts where id=$1 and workspace_id=$2 and repository_id=$3",[artifactId,c.identity.workspaceId,repositoryId])).rows[0];if(!artifact)throw new SupplyChainError(404,"artifact not found");
    if(c.req.method==="GET"){scope(c.identity,"sessions:read");const r=await c.pool.query("select id,artifact_id,predicate_type,statement,signer_principal_id,signature_algorithm,public_key_fingerprint,created_at from artifact_attestations where artifact_id=$1 order by created_at desc",[artifactId]);c.send(200,r.rows);return true}
    if(c.req.method==="POST"){scope(c.identity,"sessions:write");requireActiveRepository(repositoryRecord);await entitlement(c);const b=await c.body();const predicateType=String(b.predicateType??"").trim();const keyId=String(b.signingKeyId??"").trim();const signature=String(b.signature??"").trim();if(!predicateType||predicateType.length>512)throw new SupplyChainError(400,"predicateType is required");if(!keyId||!signature)throw new SupplyChainError(400,"signingKeyId and signature are required");if(b.statement===null||typeof b.statement!=="object")throw new SupplyChainError(400,"statement object is required");bindStatement(b.statement,artifact,repositoryId);const keyRow=(await c.pool.query("select * from principal_signing_keys where id=$1 and workspace_id=$2 and principal_id=$3 and status='active'",[keyId,c.identity.workspaceId,c.identity.principalId])).rows[0];if(!keyRow)throw new SupplyChainError(403,"active signing key not owned by principal");const payload=Buffer.from(canonical(b.statement));let signatureBytes;try{signatureBytes=Buffer.from(signature,"base64")}catch{throw new SupplyChainError(400,"signature must be base64")};if(!signatureBytes.length||!verify(null,payload,ed25519Key(keyRow.public_key_pem),signatureBytes))throw new SupplyChainError(400,"attestation signature verification failed");const r=await c.pool.query(`insert into artifact_attestations(artifact_id,predicate_type,statement,signer_principal_id,signature_algorithm,signature,public_key_fingerprint,signing_key_id) values($1,$2,$3,$4,'ed25519',$5,$6,$7) returning id,artifact_id,predicate_type,statement,signer_principal_id,signature_algorithm,public_key_fingerprint,created_at`,[artifactId,predicateType,JSON.stringify(b.statement),c.identity.principalId,signature,keyRow.fingerprint_sha256,keyId]);c.send(201,r.rows[0]);return true}
  }
  return false
}
