import http from "node:http";
import { createCipheriv, createHash, randomBytes, randomUUID } from "node:crypto";
import { Pool } from "pg";

const port=Number(process.env.WORKFLOW_PORT??4400),databaseUrl=process.env.DATABASE_URL??"postgresql://sessions:sessions@localhost:5432/sessions",maxBody=Number(process.env.SESSIONS_MAX_BODY_BYTES??1_048_576);
const pool=new Pool({connectionString:databaseUrl,max:Number(process.env.SESSIONS_WORKFLOW_DB_POOL_MAX??10)});
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
type Identity={workspaceId:string;principalId:string;scopes:string[]};
type Step={name:string;category:string;image:string;command:string[];timeoutSeconds:number;network:"none"|"egress";secrets:string[]};
const categories=new Set(["build","test","security","policy","verification","deployment"]),triggersAllowed=new Set(["push","pull_request","manual"]);
function send(res:http.ServerResponse,status:number,body:unknown){res.writeHead(status,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify(body))}function hashToken(token:string){return createHash("sha256").update(token).digest("hex")}
async function jsonBody(req:http.IncomingMessage){const chunks:Buffer[]=[];let size=0;for await(const chunk of req){const b=Buffer.from(chunk);size+=b.length;if(size>maxBody)throw new HttpError(413,"request body too large");chunks.push(b)}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString("utf8"))}catch{throw new HttpError(400,"invalid JSON body")}}
async function authenticate(req:http.IncomingMessage):Promise<Identity>{const auth=req.headers.authorization;if(!auth?.startsWith("Bearer "))throw new HttpError(401,"bearer token required");const r=await pool.query(`select c.workspace_id,c.principal_id,c.scopes from api_credentials c join principals p on p.id=c.principal_id where c.token_hash=$1 and c.status='active' and p.status='active' and (c.expires_at is null or c.expires_at>now())`,[hashToken(auth.slice(7).trim())]);if(!r.rowCount)throw new HttpError(401,"invalid or expired credential");return{workspaceId:r.rows[0].workspace_id,principalId:r.rows[0].principal_id,scopes:r.rows[0].scopes??[]}}
function requireScope(i:Identity,s:string){if(!i.scopes.includes("*")&&!i.scopes.includes(s)&&!i.scopes.includes("sessions:write"))throw new HttpError(403,`missing scope: ${s}`)}async function assertRepo(i:Identity,id:string){const r=await pool.query("select id from hosted_repositories where id=$1 and workspace_id=$2",[id,i.workspaceId]);if(!r.rowCount)throw new HttpError(404,"repository not found")}
function secretName(value:unknown){const name=String(value??"").trim();if(!/^[A-Z_][A-Z0-9_]{0,63}$/.test(name))throw new HttpError(400,"secret names must match [A-Z_][A-Z0-9_]{0,63}");return name}
function actionKey(){const raw=process.env.SESSIONS_ACTION_SECRET_KEY;if(!raw)throw new HttpError(503,"Actions secret encryption key is not configured");let key:Buffer;try{key=/^[a-f0-9]{64}$/i.test(raw)?Buffer.from(raw,"hex"):Buffer.from(raw,"base64")}catch{throw new HttpError(503,"Actions secret encryption key is invalid")};if(key.length!==32)throw new HttpError(503,"Actions secret encryption key must decode to 32 bytes");return key}
function encryptSecret(value:string){const nonce=randomBytes(12),cipher=createCipheriv("aes-256-gcm",actionKey(),nonce),ciphertext=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]),tag=cipher.getAuthTag();return{ciphertext:ciphertext.toString("base64"),nonce:nonce.toString("base64"),authTag:tag.toString("base64")}}
function validateDefinition(body:any){const name=String(body.name??"").trim();if(name.length<1||name.length>120)throw new HttpError(400,"workflow name is required and must be <=120 characters");const triggers=Array.isArray(body.triggers)&&body.triggers.length?body.triggers.map(String):["push"];if(triggers.length>3||triggers.some((x:string)=>!triggersAllowed.has(x)))throw new HttpError(400,"workflow triggers must be push, pull_request, or manual");const raw=Array.isArray(body.steps)?body.steps:[];if(!raw.length||raw.length>20)throw new HttpError(400,"workflow must contain between 1 and 20 steps");const steps:Step[]=raw.map((s:any,index:number)=>{const stepName=String(s.name??`Step ${index+1}`).trim(),category=String(s.category??"test"),image=String(s.image??"node:22-alpine").trim(),command=Array.isArray(s.command)?s.command.map(String):[],timeoutSeconds=Number(s.timeoutSeconds??900),network=s.network==="egress"?"egress":"none",secrets=Array.isArray(s.secrets)?[...new Set(s.secrets.map(secretName))]:[];if(stepName.length<1||stepName.length>120)throw new HttpError(400,`invalid step name at ${index}`);if(!categories.has(category))throw new HttpError(400,`invalid step category: ${category}`);if(!/^[A-Za-z0-9._/@:-]{1,200}$/.test(image)||image.includes(".."))throw new HttpError(400,`invalid container image: ${image}`);if(!command.length||command.length>32||command.some(v=>!v||v.length>4096))throw new HttpError(400,`step ${stepName} command must be an argv array of 1-32 strings`);if(!Number.isInteger(timeoutSeconds)||timeoutSeconds<1||timeoutSeconds>3600)throw new HttpError(400,`step ${stepName} timeout must be 1-3600 seconds`);if(secrets.length>32)throw new HttpError(400,`step ${stepName} references too many secrets`);return{name:stepName,category,image,command,timeoutSeconds,network,secrets}});return{name,triggers,steps}}
async function enqueue(i:Identity,repositoryId:string,workflow:any,commitId:string,pullRequestId?:string|null){const exists=await pool.query("select 1 from sessions_repository_checkpoints where repository_id=$1 and checkpoint_id=$2",[repositoryId,commitId]);if(!exists.rowCount)throw new HttpError(400,"commitId must identify a Sessions-native commit in this repository");const client=await pool.connect();try{await client.query("begin");const runId=randomUUID();await client.query("insert into action_runs(id,workspace_id,repository_id,commit_id,pull_request_id,trigger,status,actor_principal_id,workflow_id,workflow_name,execution_kind) values($1,$2,$3,$4,$5,'manual','queued',$6,$7,$8,'customer_workflow')",[runId,i.workspaceId,repositoryId,commitId,pullRequestId??null,i.principalId,workflow.id,workflow.name]);for(const step of workflow.definition.steps as Step[])await client.query("insert into action_checks(action_run_id,name,category,status,command_argv,container_image,timeout_seconds,network_policy,secret_names) values($1,$2,$3,'queued',$4,$5,$6,$7,$8)",[runId,step.name,step.category,JSON.stringify(step.command),step.image,step.timeoutSeconds,step.network??"none",JSON.stringify(step.secrets??[])]);await client.query("commit");return{runId,status:"queued"}}catch(e){await client.query("rollback");throw e}finally{client.release()}}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url??"/",`http://${req.headers.host??"localhost"}`);if(req.method==="GET"&&url.pathname==="/health"){await pool.query("select 1");return send(res,200,{ok:true,service:"sessions-workflows"})}const identity=await authenticate(req);let m=url.pathname.match(/^\/api\/repositories\/([^/]+)\/workflows$/);if(m){const repositoryId=decodeURIComponent(m[1]);await assertRepo(identity,repositoryId);if(req.method==="GET"){requireScope(identity,"sessions:read");const r=await pool.query("select id,name,enabled,triggers,definition,created_at,updated_at from repository_action_workflows where workspace_id=$1 and repository_id=$2 order by name",[identity.workspaceId,repositoryId]);return send(res,200,r.rows)}if(req.method==="POST"){requireScope(identity,"sessions:write");const d=validateDefinition(await jsonBody(req));const r=await pool.query(`insert into repository_action_workflows(workspace_id,repository_id,name,enabled,triggers,definition,created_by) values($1,$2,$3,true,$4,$5,$6) on conflict(repository_id,name) do update set triggers=excluded.triggers,definition=excluded.definition,enabled=true,updated_at=now() returning id,name,enabled,triggers,definition,created_at,updated_at`,[identity.workspaceId,repositoryId,d.name,d.triggers,JSON.stringify({version:1,steps:d.steps}),identity.principalId]);return send(res,201,r.rows[0])}}
m=url.pathname.match(/^\/api\/repositories\/([^/]+)\/action-secrets$/);if(m){const repositoryId=decodeURIComponent(m[1]);await assertRepo(identity,repositoryId);if(req.method==="GET"){requireScope(identity,"sessions:read");const r=await pool.query("select name,created_at,updated_at from repository_action_secrets where workspace_id=$1 and repository_id=$2 order by name",[identity.workspaceId,repositoryId]);return send(res,200,r.rows)}if(req.method==="POST"){requireScope(identity,"sessions:write");const b=await jsonBody(req),name=secretName(b.name),value=String(b.value??"");if(!value||value.length>65536)throw new HttpError(400,"secret value is required and must be <=64KiB");const encrypted=encryptSecret(value);await pool.query(`insert into repository_action_secrets(workspace_id,repository_id,name,ciphertext,nonce,auth_tag,created_by) values($1,$2,$3,$4,$5,$6,$7) on conflict(repository_id,name) do update set ciphertext=excluded.ciphertext,nonce=excluded.nonce,auth_tag=excluded.auth_tag,created_by=excluded.created_by,updated_at=now()`,[identity.workspaceId,repositoryId,name,encrypted.ciphertext,encrypted.nonce,encrypted.authTag,identity.principalId]);return send(res,201,{name,stored:true})}}
m=url.pathname.match(/^\/api\/repositories\/([^/]+)\/action-secrets\/([^/]+)\/delete$/);if(m&&req.method==="POST"){const repositoryId=decodeURIComponent(m[1]),name=secretName(decodeURIComponent(m[2]));await assertRepo(identity,repositoryId);requireScope(identity,"sessions:write");await pool.query("delete from repository_action_secrets where workspace_id=$1 and repository_id=$2 and name=$3",[identity.workspaceId,repositoryId,name]);return send(res,200,{name,deleted:true})}
m=url.pathname.match(/^\/api\/repositories\/([^/]+)\/workflows\/([^/]+)\/(run|enable|disable)$/);if(m&&req.method==="POST"){const repositoryId=decodeURIComponent(m[1]),workflowId=decodeURIComponent(m[2]),action=m[3];await assertRepo(identity,repositoryId);requireScope(identity,"sessions:write");const w=(await pool.query("select * from repository_action_workflows where id=$1 and workspace_id=$2 and repository_id=$3",[workflowId,identity.workspaceId,repositoryId])).rows[0];if(!w)throw new HttpError(404,"workflow not found");if(action==="enable"||action==="disable"){const enabled=action==="enable";await pool.query("update repository_action_workflows set enabled=$2,updated_at=now() where id=$1",[workflowId,enabled]);return send(res,200,{id:workflowId,enabled})}const b=await jsonBody(req);return send(res,202,await enqueue(identity,repositoryId,w,String(b.commitId??""),b.pullRequestId??null))}
m=url.pathname.match(/^\/api\/repositories\/([^/]+)\/action-runs\/([^/]+)$/);if(m&&req.method==="GET"){const repositoryId=decodeURIComponent(m[1]),runId=decodeURIComponent(m[2]);await assertRepo(identity,repositoryId);requireScope(identity,"sessions:read");const run=(await pool.query("select * from action_runs where id=$1 and workspace_id=$2 and repository_id=$3",[runId,identity.workspaceId,repositoryId])).rows[0];if(!run)throw new HttpError(404,"action run not found");const checks=await pool.query("select id,name,category,status,conclusion,summary,evidence,container_image,command_argv,timeout_seconds,network_policy,secret_names,log_text,exit_code,started_at,completed_at from action_checks where action_run_id=$1 order by started_at nulls first,id",[runId]);return send(res,200,{...run,checks:checks.rows})}
throw new HttpError(404,"not found")}catch(error){const status=error instanceof HttpError?error.status:500,message=error instanceof Error?error.message:"internal error";console.error(JSON.stringify({level:"error",service:"sessions-workflows",status,message}));return send(res,status,{error:status>=500?"internal error":message})}});
server.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({level:"info",event:"workflows.started",port})));async function shutdown(){server.close(async()=>{await pool.end();process.exit(0)});setTimeout(()=>process.exit(1),10_000).unref()}process.on("SIGTERM",()=>void shutdown());process.on("SIGINT",()=>void shutdown());
