"use client";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";

type Member={id:string;display_name:string;email?:string|null;kind:string;status:string;role:string;created_at:string};
type Invitation={id:string;email:string;role:string;status:string;expires_at:string;created_at:string};
type WorkspacePayload={workspace:{id:string;name:string;status:string};current:{principalId:string;role:string};members:Member[];invitations:Invitation[]};
type Billing={plan_key?:string;status?:string;payment_state?:string;entitlement_status?:string;entitlement_reason?:string;subscription_status?:string;period_end?:string|null;cancel_at_period_end?:boolean};

export function SettingsClient(){
 const [workspace,setWorkspace]=useState<WorkspacePayload|null>(null),[billing,setBilling]=useState<Billing|null>(null),[email,setEmail]=useState(""),[role,setRole]=useState("member"),[inviteLink,setInviteLink]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const api=typeof window!=="undefined"?window.location.origin:"";const token=typeof window!=="undefined"?localStorage.getItem("sessions_api_token"):null;const headers=useMemo(()=>({authorization:`Bearer ${token??""}`,"content-type":"application/json"}),[token]);
 const request=useCallback(async(path:string,options:RequestInit={})=>{if(!token)throw new Error("Sign in to Sessions first.");const r=await fetch(`${api}${path}`,{...options,headers:{...headers,...(options.headers||{})},cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??`HTTP ${r.status}`);return b;},[api,headers,token]);
 const load=useCallback(async()=>{try{setError("");const[w,b]=await Promise.all([request("/api/auth/workspace"),request("/api/billing/subscription")]);setWorkspace(w);setBilling(b);}catch(e){setError(e instanceof Error?e.message:"Could not load settings.");}},[request]);
 useEffect(()=>{void load();},[load]);
 async function invite(){setBusy("invite");setError("");try{const result=await request("/api/auth/workspace/invitations",{method:"POST",body:JSON.stringify({email,role})});setInviteLink(`${window.location.origin}/invite?token=${encodeURIComponent(result.inviteToken)}`);setEmail("");await load();}catch(e){setError(e instanceof Error?e.message:"Invite failed.");}finally{setBusy("");}}
 async function memberAction(member:Member,action:"remove"|"role",nextRole?:string){setBusy(`${action}:${member.id}`);try{await request(`/api/auth/workspace/members/${encodeURIComponent(member.id)}/${action}`,{method:"POST",body:JSON.stringify(nextRole?{role:nextRole}:{})});await load();}catch(e){setError(e instanceof Error?e.message:"Member update failed.");}finally{setBusy("");}}
 async function exportData(){setBusy("export");try{const r=await fetch(`${api}/api/account/export`,{method:"POST",headers:{authorization:`Bearer ${token??""}`}});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??`HTTP ${r.status}`);}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`sessions-export-${Date.now()}.json`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Export failed.");}finally{setBusy("");}}
 async function cancel(){if(!confirm("Cancel the active Sessions subscription at the end of the billing period?"))return;setBusy("cancel");try{await request("/api/account/cancel",{method:"POST",body:"{}"});await load();}catch(e){setError(e instanceof Error?e.message:"Cancellation failed.");}finally{setBusy("");}}
 const admin=workspace?.current.role==="owner"||workspace?.current.role==="admin";
 return <main className="section-narrow" style={{paddingTop:34,paddingBottom:80}}><div className="breadcrumb"><Link href="/dashboard">Dashboard</Link> / Settings</div><header className="workspace-header" style={{marginBottom:24}}><div><h1>Settings</h1><p>Workspace, team, billing, exports and account lifecycle.</p></div></header>{error?<div className="sessions-empty" style={{marginBottom:16}}><strong>Settings action failed.</strong>{error}</div>:null}
 <section className="workspace-panel" style={{padding:22,marginBottom:16}}><h2 style={{marginTop:0}}>Workspace</h2><div className="sessions-side-panel"><Row label="Name" value={workspace?.workspace.name??"Loading…"}/><Row label="Your role" value={workspace?.current.role??"—"}/><Row label="Workspace status" value={workspace?.workspace.status??"—"}/></div></section>
 <section className="workspace-panel" style={{padding:22,marginBottom:16}}><div className="panel-head" style={{padding:0,paddingBottom:16}}><div><h2>Team</h2><p>Owners and admins can invite collaborators and change access immediately.</p></div></div>{admin?<div style={{display:"grid",gridTemplateColumns:"1fr 150px auto",gap:10,marginBottom:16}}><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="teammate@example.com" style={field}/><select value={role} onChange={e=>setRole(e.target.value)} style={field}><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option></select><button className="button button-primary" disabled={!email||busy==="invite"} onClick={invite}>{busy==="invite"?"Inviting…":"Invite"}</button></div>:null}{inviteLink?<div className="sessions-empty" style={{marginBottom:14}}><strong>Invite created.</strong><span>Copy this secure link and send it to the recipient:</span><code style={{wordBreak:"break-all"}}>{inviteLink}</code></div>:null}<div className="session-feed">{workspace?.members.map(m=><div className="feed-row" key={m.id} style={{gridTemplateColumns:"34px 1fr auto"}}><span className="feed-symbol">◎</span><span className="feed-copy"><strong>{m.display_name}</strong><span>{m.email??m.kind} · {m.status}</span></span><div style={{display:"flex",gap:7,alignItems:"center"}}>{admin&&m.role!=="owner"?<><select value={m.role} onChange={e=>void memberAction(m,"role",e.target.value)} style={{...field,minHeight:34,width:110}}><option value="admin">admin</option><option value="member">member</option><option value="viewer">viewer</option></select><button className="button button-danger" onClick={()=>void memberAction(m,"remove")}>Remove</button></>:<strong>{m.role}</strong>}</div></div>)}</div>{workspace?.invitations.some(i=>i.status==="pending")?<div style={{marginTop:18}}><h3>Pending invitations</h3>{workspace.invitations.filter(i=>i.status==="pending").map(i=><div className="signal-row" key={i.id}><span>{i.email} · {i.role}</span><strong>expires {new Date(i.expires_at).toLocaleDateString()}</strong></div>)}</div>:null}</section>
 <section className="workspace-panel" style={{padding:22,marginBottom:16}}><h2 style={{marginTop:0}}>Billing</h2><div className="sessions-side-panel"><Row label="Plan" value={billing?.plan_key??"—"}/><Row label="Entitlement" value={billing?.entitlement_status??billing?.status??"—"}/><Row label="Payment" value={billing?.payment_state??"—"}/><Row label="Subscription" value={billing?.subscription_status??"—"}/><Row label="Renews / ends" value={billing?.period_end?new Date(billing.period_end).toLocaleDateString():"—"}/></div><div style={{display:"flex",gap:10,marginTop:16}}><Link className="button button-secondary" href="/pricing">Change plan</Link>{billing?.subscription_status&&!billing.cancel_at_period_end?<button className="button button-danger" onClick={cancel} disabled={busy==="cancel"}>{busy==="cancel"?"Cancelling…":"Cancel subscription"}</button>:null}</div></section>
 <section className="workspace-panel" style={{padding:22}}><h2 style={{marginTop:0}}>Your data</h2><p style={{color:"var(--muted)"}}>Export the complete workspace record, including repositories, Sessions evidence, billing, usage and audit history.</p><button className="button button-secondary" onClick={exportData} disabled={busy==="export"}>{busy==="export"?"Preparing…":"Export workspace data"}</button></section></main>;
}
function Row({label,value}:{label:string;value:string}){return <div className="signal-row"><span>{label}</span><strong>{value}</strong></div>}
const field:React.CSSProperties={minHeight:40,borderRadius:9,border:"1px solid var(--border)",background:"#0b1017",color:"var(--text)",padding:"0 11px",font:"inherit",width:"100%"};
