import { access, readFile, readdir } from 'node:fs/promises';
import { constants } from 'node:fs';

const requiredFiles = [
  '.env.production.example','docker-compose.production.yml','scripts/list-migrations.sh','scripts/deploy-production.sh','scripts/backup-production.sh','scripts/restore-production.sh','scripts/rollback-production.sh','scripts/check-production-slo.sh','scripts/provision-workspace.sh','scripts/qualify-billing.mjs','scripts/qualify-lifecycle.mjs','scripts/qualify-native-collaboration.mjs','scripts/qualify-postgres.sh','scripts/qualify-current-postgres.sh','scripts/qualify-current-recovery.sh','scripts/qualify-webhook-outbox.sh','scripts/qualify-release-governance.sh','scripts/qualify-native-webhooks.sh','scripts/qualify-repository-lifecycle.sh','scripts/qualify-supply-chain.sh','scripts/qualify-team-auth.mjs','scripts/qualify-tenancy.mjs','scripts/validate-production-config.sh','infrastructure/docker/init-postgres.sh',
  'apps/api/src/auth-server.ts','apps/api/src/billing-server.ts','apps/api/src/repository-server.ts','apps/api/src/organization-security.ts','apps/api/src/enterprise-governance.ts','apps/api/src/enterprise-governance.test.ts','apps/api/src/private-runner-server.ts','apps/api/src/release-governance.ts','apps/api/src/repository-lifecycle.ts','apps/api/src/supply-chain.ts','apps/api/src/supply-chain.test.ts','apps/api/src/workflow-server.ts','apps/api/src/webhook-server.ts','apps/api/src/webhook-worker.ts','apps/api/src/webhook-crypto.ts','apps/api/src/webhooks.ts','apps/api/src/observability.ts','apps/runner/src/workflow-executor.ts',
  'apps/web/app/settings/page.tsx','apps/web/app/invite/page.tsx','apps/web/app/repositories/[id]/releases/page.tsx','apps/web/app/repositories/[id]/deployments/page.tsx','apps/web/app/repositories/[id]/settings/page.tsx','apps/web/app/repositories/[id]/actions/[runId]/page.tsx',
];
const migrationNames=(await readdir('infrastructure/postgres')).filter(name=>/^\d{3}-.*\.sql$/.test(name)).sort();
const requiredMigrations=['infrastructure/postgres/init.sql',...migrationNames.map(name=>`infrastructure/postgres/${name}`)];
const productionEnvKeys=['SESSIONS_DOMAIN','POSTGRES_USER','POSTGRES_PASSWORD','POSTGRES_DB','REDIS_PASSWORD','MINIO_ROOT_USER','MINIO_ROOT_PASSWORD','S3_BUCKET','SESSIONS_ACTION_SECRET_KEY','SESSIONS_WEBHOOK_MASTER_KEY','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','STRIPE_PRICE_DEVELOPER'];
const productionServices=['proxy','web','api','auth','repositories','workflows','private-runners','webhooks','webhook-worker','billing','runner','executor','postgres','redis','minio'];
async function requireFile(path){try{await access(path,constants.R_OK)}catch{throw new Error(`Launch-critical asset missing or unreadable: ${path}`)}}
function requireIn(text,invariants,label){for(const invariant of invariants)if(!text.includes(invariant))throw new Error(`${label} invariant missing: ${invariant}`)}

async function main(){
  for(const path of [...requiredFiles,...requiredMigrations])await requireFile(path);
  if(!migrationNames.length)throw new Error('No numbered production migrations found');
  const pkg=JSON.parse(await readFile('package.json','utf8')),scripts=pkg.scripts??{};
  for(const script of ['verify','qualify:launch','test:native','test:commercial','test:api','test:runner','docker:up','docker:down'])if(!scripts[script])throw new Error(`Launch-critical package script missing: ${script}`);
  const envTemplate=await readFile('.env.production.example','utf8');for(const key of productionEnvKeys)if(!new RegExp(`^${key}=`, 'm').test(envTemplate))throw new Error(`Production environment contract missing ${key}`);
  const compose=await readFile('docker-compose.production.yml','utf8');for(const service of productionServices)if(!new RegExp(`^\\s{2}${service}:`,'m').test(compose))throw new Error(`Production topology missing service: ${service}`);
  requireIn(compose,['DATABASE_URL: postgresql://${POSTGRES_USER','SESSIONS_PUBLIC_ORIGIN: https://${SESSIONS_DOMAIN}','STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:','STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:','SESSIONS_ALLOW_INSECURE_LOCAL: "false"','SESSIONS_ACTION_SECRET_KEY: ${SESSIONS_ACTION_SECRET_KEY:','SESSIONS_WEBHOOK_MASTER_KEY: ${SESSIONS_WEBHOOK_MASTER_KEY:','SESSIONS_ALLOW_INSECURE_WEBHOOKS: "false"','PRIVATE_RUNNER_PORT: 4600','./infrastructure/postgres:/sessions-migrations:ro','./infrastructure/docker/init-postgres.sh:/docker-entrypoint-initdb.d/001-sessions-migrations.sh:ro'],'Production topology');
  const billing=await readFile('apps/api/src/billing-server.ts','utf8');requireIn(billing,['verifyStripeSignature','usage_events','workspace_entitlements','api_credentials'],'Billing/entitlement');
  const repositoryServer=await readFile('apps/api/src/repository-server.ts','utf8');requireIn(repositoryServer,['repository_branch_policies','requiredHumanApprovals','branch-policies','handleOrganizationSecurity','handleReleaseGovernance','handleRepositoryLifecycle','handleSupplyChain'],'Repository governance');
  const organizationSecurity=await readFile('apps/api/src/organization-security.ts','utf8');requireIn(organizationSecurity,['organization_security_policies','requireEnterpriseHumanAdmin','active Enterprise entitlement','organization.security_policy.update','handleEnterpriseGovernance'],'Organization security');
  const enterprise=await readFile('apps/api/src/enterprise-governance.ts','utf8');requireIn(enterprise,['organization.audit_export','organization.retention_policy.update','organization.retention_sweep','legal hold','confirmOrganizationId','sha256'],'Enterprise governance');
  const privateRunners=await readFile('apps/api/src/private-runner-server.ts','utf8');requireIn(privateRunners,['Runner ','runner_lease_expires_at',"execution_target in ('private','either')",'required workflow secrets are missing','private_runner.job_complete','max_concurrency'],'Private runner');
  const release=await readFile('apps/api/src/release-governance.ts','utf8');requireIn(release,['environment-policies','deployment_approvals','requiredHumanApprovals','restrictAiDeploy','requireAttestedArtifact','requireSbom'],'Release/deployment governance');
  const lifecycle=await readFile('apps/api/src/repository-lifecycle.ts','utf8');requireIn(lifecycle,['requireHumanAdmin','schedule_delete','confirmRepositoryId','sessions.lifecycle_purge'],'Repository lifecycle');
  const supply=await readFile('apps/api/src/supply-chain.ts','utf8');requireIn(supply,['principal_signing_keys','repository_artifacts','artifact_attestations','Ed25519','signature verification failed','subject digest does not match artifact','repository does not match artifact','repository is read-only'],'Supply chain');
  const caddy=await readFile('infrastructure/docker/Caddyfile','utf8');requireIn(caddy,['/api/organization/security-policy','/api/organization/audit-export','/api/organization/retention-policy','/api/private-runners','/api/private-runner/*','runner-policy','reverse_proxy private-runners:4600','branch-policies','environment-policies','signing-keys','artifacts'],'Production routing');
  const webhookWorker=await readFile('apps/api/src/webhook-worker.ts','utf8');requireIn(webhookWorker,['x-sessions-signature-256','createHmac','lease_expires_at','maxAttempts','assertSafeWebhookUrl'],'Webhook delivery');
  const orgPolicy=await readFile('infrastructure/postgres/026-organization-security-policy.sql','utf8');requireIn(orgPolicy,['organization_security_policies','sessions_enforce_branch_policy_floor','sessions_enforce_environment_policy_floor','effective branch policy','effective environment policy'],'Organization policy schema');
  const retention=await readFile('infrastructure/postgres/028-enterprise-audit-retention.sql','utf8');requireIn(retention,['organization_retention_policies','organization_audit_events','legal_hold'],'Enterprise retention schema');
  const runnerSchema=await readFile('infrastructure/postgres/029-private-runners.sql','utf8');requireIn(runnerSchema,['private_runners','repository_runner_policies',"'private_workflow'",'sessions_apply_runner_policy'],'Private runner schema');
  const hostedExecutor=await readFile('apps/runner/src/workflow-executor.ts','utf8');requireIn(hostedExecutor,["execution_kind='customer_workflow'",'defaultNetwork: "none"','"--read-only"','"--cap-drop"','"no-new-privileges:true"','secretsRedacted: true'],'Hosted executor isolation');
  const recovery=await readFile('scripts/qualify-current-recovery.sh','utf8');requireIn(recovery,['pg_dump','pg_restore','repository_artifacts','artifact_attestations','principal_signing_keys','organization_security_policies'],'Current recovery');
  console.log(JSON.stringify({status:'internally-launch-ready-structure',checkedAt:new Date().toISOString(),assets:requiredFiles.length,migrations:requiredMigrations.length,latestMigration:migrationNames.at(-1),productionServices,externalProofStillRequired:['live production deployment against real secrets/domains','real Stripe test/live-mode account qualification','external-user onboarding and collaboration acceptance run','real customer payment and retention evidence']},null,2));
}
await main();
