"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";

export default function InvitePage(){return <Suspense fallback={<InviteLoading/>}><InviteForm/></Suspense>}

function InviteLoading(){return <main className="commerce-page"><section className="commerce-shell"><div className="commerce-card"><div className="eyebrow">Workspace invitation</div><h1>Loading invitation…</h1><p>Preparing the workspace invitation securely.</p></div></section></main>}

function InviteForm(){const params=useSearchParams(),inviteToken=params.get("token")??"",[displayName,setDisplayName]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function accept(){setBusy(true);setError("");try{const r=await fetch("/api/auth/invitations/accept",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({inviteToken,displayName,password})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??`HTTP ${r.status}`);localStorage.setItem("sessions_api_token",b.token);localStorage.setItem("sessions_workspace_id",b.workspaceId);location.href="/dashboard";}catch(e){setError(e instanceof Error?e.message:"Could not accept invitation.");setBusy(false);}}return <main className="commerce-page"><section className="commerce-shell"><div className="commerce-card"><div className="eyebrow">Workspace invitation</div><h1>Join this Sessions workspace</h1><p>If you already have a Sessions account, enter that account password. If this is your first Sessions workspace, choose your display name and a password of at least 12 characters.</p>{!inviteToken?<div className="sessions-empty"><strong>Invalid invitation link.</strong>The invite token is missing.</div>:<><label className="commerce-field">Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Your name"/></label><label className="commerce-field">Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="12+ characters"/></label>{error?<div className="commerce-error">{error}</div>:null}<button className="button button-primary button-full" disabled={busy||password.length<12} onClick={accept}>{busy?"Joining…":"Accept invitation"}</button></>}<p style={{marginTop:18}}><Link href="/">Back to Sessions</Link></p></div></section></main>}
