import {
  checkoutWorkstream, createCheckpoint, createWorkstream, getActiveWorkstream, integrateWorkstream, listHistory, listStaged, listWorkstreams,
  previewIntegration, previewRestore, repositoryDiff, repositoryStatus, restoreCheckpoint, stagePaths, stagedDiff, unstagePaths, unstagedDiff, verifyRepositoryIntegrity,
} from "@sessions/native-repository";
import { cloneRepository, createTag, deleteTag, fetchRemote, importGitRepository, listRemotes, listTags, pullRemote, pushRemote, removeRemote, revertCheckpoint, setRemote } from "@sessions/native-repository/transport";

function marker(kind:string){return kind==="added"?"+":kind==="removed"?"-":"~"}
function printChanges(changes:Array<{path:string;kind:string}>,empty="No changes."){if(!changes.length)return console.log(empty);for(const change of changes)console.log(`${marker(change.kind)} ${change.path}`)}
export async function handleNativeCommand(command:string|undefined,args:string[],root:string):Promise<boolean>{switch(command){
case"clone":{if(args.length<2)throw new Error("Usage: sessions clone <source> <destination>");const r=await cloneRepository(args[0],args[1]);console.log(`Cloned ${r.name} → ${args[1]}`);return true;}
case"import":{const source=args[0]??root;const destination=args[1];const r=await importGitRepository(source,destination);console.log(`Imported Git repository\nCommits ${r.commits}\nBranches ${r.branches}\nTags ${r.tags}\nRepository ${r.repository.id}`);return true;}
case"remote":{const[action,name,url]=args;if(!action||action==="list"){for(const r of await listRemotes(root))console.log(`${r.name}\t${r.url}`);return true;}if(action==="add"||action==="set"){if(!name||!url)throw new Error("Usage: sessions remote add <name> <url>");const r=await setRemote(root,name,url);console.log(`${r.name}\t${r.url}`);return true;}if(action==="remove"){if(!name)throw new Error("Usage: sessions remote remove <name>");await removeRemote(root,name);console.log(`Removed remote ${name}`);return true;}throw new Error("Usage: sessions remote <list|add|set|remove>");}
case"fetch":{const r=await fetchRemote(root,args[0]??"origin");console.log(`Fetched ${r.remote} at ${r.fetchedAt}`);return true;}
case"push":{const r=await pushRemote(root,args[0]??"origin");console.log(`Pushed ${r.remote} at ${r.pushedAt}`);return true;}
case"pull":{const r=await pullRemote(root,args[0]??"origin");console.log(`Pulled ${r.remote}\nHead ${r.headCheckpointId??"empty"}`);return true;}
case"tag":{const[action,...rest]=args;if(!action||action==="list"){for(const t of await listTags(root))console.log(`${t.name}\t${t.checkpointId}`);return true;}if(action==="create"){if(!rest[0])throw new Error("Usage: sessions tag create <name> [checkpoint]");const t=await createTag(root,rest[0],rest[1]);console.log(`${t.name}\t${t.checkpointId}`);return true;}if(action==="delete"){if(!rest[0])throw new Error("Usage: sessions tag delete <name>");await deleteTag(root,rest[0]);console.log(`Deleted tag ${rest[0]}`);return true;}throw new Error("Usage: sessions tag <list|create|delete>");}
case"revert":{if(!args[0])throw new Error("Usage: sessions revert <checkpoint>");const r=await revertCheckpoint(root,args[0]);console.log(`Reverted ${r.target.friendlyName}\nCreated ◆ ${r.reverted.friendlyName}\n${r.reverted.id}`);return true;}
case"status":{const s=await repositoryStatus(root);console.log(`${s.repository.name}\n\nWorkstream   ${s.workstream.name}\nHead         ${s.headCheckpoint?.friendlyName??"No checkpoint"}\nState        ${s.clean?"Clean":"Changes present"}\nStaged       ${s.stagedChanges.length}\nUnstaged     ${s.unstagedChanges.length}`);if(s.stagedChanges.length){console.log("\nStaged Changes");printChanges(s.stagedChanges)}if(s.unstagedChanges.length){console.log("\nChanges");printChanges(s.unstagedChanges)}return true;}
case"add":{const staged=await stagePaths(root,args.length?args:["."]);console.log(`Staged ${staged.length} path(s).`);printChanges(await stagedDiff(root),"Nothing staged.");return true;}
case"unstage":{const remaining=await unstagePaths(root,args.length?args:["."]);console.log(remaining.length?`${remaining.length} staged path(s) remain.`:"Stage cleared.");return true;}
case"staged":{const staged=await listStaged(root);if(!staged.length)console.log("Nothing staged.");else for(const item of staged)console.log(`${item.operation==="remove"?"-":"+"} ${item.path}`);return true;}
case"diff":{if(args.includes("--staged"))printChanges(await stagedDiff(root),"No staged changes.");else if(args.includes("--unstaged"))printChanges(await unstagedDiff(root),"No unstaged changes.");else printChanges(await repositoryDiff(root),"No changes.");return true;}
case"work":{const objective=args.join(" ").trim();if(!objective)throw new Error("Usage: sessions work <objective>");const current=await getActiveWorkstream(root);const slug=objective.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48)||`work-${Date.now()}`;const created=await createWorkstream(root,{name:slug,objective,fromCheckpointId:current.headCheckpointId});const active=await checkoutWorkstream(root,created.id);console.log(`Workstream ${active.name}\nObjective: ${objective}\n${active.id}`);return true;}
case"workstream":{const[action,value,...objectiveParts]=args;if(action==="list"){const active=await getActiveWorkstream(root);for(const item of await listWorkstreams(root))console.log(`${item.id===active.id?"●":"○"} ${item.name}${item.objective?` — ${item.objective}`:""}`);return true;}if(action==="create"){if(!value)throw new Error("Usage: sessions workstream create <name> [objective]");const current=await getActiveWorkstream(root);const created=await createWorkstream(root,{name:value,objective:objectiveParts.join(" ")||undefined,fromCheckpointId:current.headCheckpointId});const active=await checkoutWorkstream(root,created.id);console.log(`Created and switched to ${active.name}\n${active.id}`);return true;}if(action==="switch"){if(!value)throw new Error("Usage: sessions workstream switch <name-or-id>");const active=await checkoutWorkstream(root,value);console.log(`Active Workstream: ${active.name}\n${active.id}`);return true;}throw new Error("Usage: sessions workstream <list|create|switch>");}
case"switch":{const reference=args.join(" ").trim();if(!reference)throw new Error("Usage: sessions switch <name-or-id>");const active=await checkoutWorkstream(root,reference);console.log(`Active Workstream: ${active.name}\n${active.id}`);return true;}
case"history":{const history=await listHistory(root);if(!history.length)console.log("No Checkpoints yet.");else for(const cp of history)console.log(`◆ ${cp.friendlyName}\n  ${cp.id}  ${cp.lifecycle}  ${cp.createdAt}`);return true;}
case"integrate":{const source=args.find(v=>v!=="--apply");if(!source)throw new Error("Usage: sessions integrate <workstream> [--apply]");const preview=await previewIntegration(root,source);console.log(`Integration Preview\n\nSource       ${preview.source.name}\nTarget       ${preview.target.name}\nIncoming     ${preview.incomingChanges.length}\nTarget work  ${preview.targetChanges.length}\nConflicts    ${preview.conflicts.length}\nMode         ${preview.fastForward?"Fast-forward":"Three-way"}`);if(!args.includes("--apply"))console.log("\nPreview only. Re-run with --apply to integrate.");else{const result=await integrateWorkstream(root,source);console.log(result.checkpoint?`\nIntegrated ${preview.source.name} → ${preview.target.name}\n◆ ${result.checkpoint.friendlyName}`:"\nNothing to integrate.")}return true;}
case"restore":{const reference=args.find(v=>v!=="--apply");if(!reference)throw new Error("Usage: sessions restore <checkpoint-name-or-id> [--apply]");const preview=await previewRestore(root,reference);console.log(`Restore Preview\n\nTarget: ◆ ${preview.checkpoint.friendlyName}\nAdd: ${preview.willAdd}\nModify: ${preview.willModify}\nRemove: ${preview.willRemove}\nUncheckpointed work: ${preview.dirty?"Detected":"None"}`);if(args.includes("--apply")){const staged=await listStaged(root);if(staged.length)await unstagePaths(root,["."]);const result=await restoreCheckpoint(root,reference);console.log(`\nRestored ◆ ${result.restored.friendlyName}`)}return true;}
case"integrity":{const result=await verifyRepositoryIntegrity(root);console.log(`Repository integrity: ${result.ok?"OK":"FAILED"}\nCheckpoints: ${result.checkedCheckpoints}\nObjects: ${result.checkedObjects}`);if(result.errors.length)for(const e of result.errors)console.log(`! ${e}`);if(!result.ok)process.exitCode=2;return true;}
default:return false;}}
export async function createLocalCheckpoint(root:string,name:string,sessionId?:string){return createCheckpoint(root,{friendlyName:name,sessionIds:sessionId?[sessionId]:[]})}
